### ISSUE TITLE
Aurelia build resources in package.json are ignored

### ISSUE THREAD

**Issue by smax48** [aurelia/webpack-plugin#104]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.2

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
6.10.0

* **NPM Version:**
4.3.0

* **JSPM OR Webpack AND Version**
webpack 2.3.3

* **Browser:**
all 

* **Language:**
TypeScript 2.2

**Current behavior:**
I am trying to migrate our application to the new aurelia webpack plugin.
The app is using aurelia-kendoui-bridge which is loaded as a plugin.
The configuration in main.ts is the following:
```
    aurelia.use
        .plugin(PLATFORM.moduleName("aurelia-kendoui-bridge"), (kendo: KendoConfigBuilder) => 
           kendo
            .kendoTemplateSupport()
            .useValueConverters()
            .notifyBindingBehavior()
            .pro());
```
I know that internally this plugin registers a number of resources for various kendo UI widgets.
Previously I had them all listed in my package.json under aurelia/build/resourses and everything worked fine.
Now I am getting an error (regardless of what I have in package.json inside aurelia/build/resources):
```
Error: Unable to find module with ID: aurelia-kendoui-bridge/common/template
```

I added PLATFORM.moduleName in the plugin configuration, otherwise I got similar error regarding aurelia-kendoui-bridge itself.

What am I doing wrong?.. 

**Expected/desired behavior:**

* **What is the expected behavior?**
Aurelia webpack plugin should use information from package.json during the build process

* **What is the motivation / use case for changing the behavior?**

**Comment by Thanood** [comment]
I can confirm this.

My understanding is that build resources should still work. At least this is what I remember from a wiki (?) post a few weeks ago so this may be outdated. A user of aurelia-materialize-bridge created an issue with a similar problem (and a workaround) here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/401

The workaroung consist of using `ModuleDependenciesPlugin` for the resources used in `package.json` like [described here](https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies).

**Comment by jods4** [comment]
The new webpack plugins don't use Aurelia resources from `package.json` anymore. They are kept there to maintain compatibility for our 1.x users.

Dependencies are now precisely described inside code with `PLATFORM.moduleName`, which works better with Webpack in general and supports more scenarios (e.g. code splitting).

Ideally, `aurelia-materialize-bridge` will be updated to use `moduleName` and then it will just work out-of-the-box. Until then, you need to manually document those dependencies using `ModuleDependenciesPlugin`, as explained by @Thanood. The provided wiki link is also useful.

**Comment by Thanood** [comment]
Thanks for the explanation @jods4 👍 
I'll tell the Kendo bridge developers, too.

**Comment by smax48** [comment]
Thanks for the explanation!
However, I doubt that this can be easily implemented in aurelia-kendoui-bridge :) - because it is the application that decides what set of resources to load, not the library itself...

**Comment by Thanood** [comment]
@smax48 It's already done. 😏 
aurelia-kendoui-bridge just released 1.5.0 which uses `moduleName`.

**Comment by niieani** [comment]
@jods4 perhaps we could include some warning plugin which checks to see if there are any `build.resources` defined in any of the installed dependencies, which weren't added as Webpack build-time dependencies? This way migration, especially for obscure plugins, would be much simpler.

**Comment by jods4** [comment]
@niieani yes, there are several diagnostics we could add to really help people. Like detecting `globalResource()` calls without `moduleName()`, suggesting `ModuleDependenciesPlugin` based on `aurelia.build.resources`...

I'm open to PRs ;)
