### ISSUE TITLE
Code Splitting doesn't work

### ISSUE THREAD

**Issue by code-chris** [aurelia/webpack-plugin#110]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.2

**Please tell us about your environment:**
* **Operating System:**
Windows  10

* **Node Version:**
7.10.0

* **NPM Version:**
5.0.0-beta.69

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
all

* **Language:**
TypeScript 2.3.3

**Current behavior:**
I want to split my Aurelia app alongside the routes to minimize the initial chunk size. I use the second parameter from `PLATFORM.moduleName(...)` to set a chunk name. But `aurelia-webpack-plugin` doesn't split the bundle. There's only one big `main.js` at the end.
My configurations: https://gist.github.com/code-chris/4cd61329ae3967e74920a8392433466b

**Expected/desired behavior:**
The Bundle is splitted correctly

**Comment by jods4** [comment]
My guess:
That `moduleName` dependency is a splitting point but if another module in the main bundle takes a direct dependency then Webpack has to pull it up in the main bundle (with its deps, etc). 
If the second chunk ends up being empty it's not created.

Try `--display-modules --display-reasons` to find out your exact dependencies.

**Comment by code-chris** [comment]
When I interpret this correctly:

```
[async!masterdata/Masterdata] ./~/bundle-loader?lazy&name=masterdata!./app/masterdata/Masterdata.ts 250 bytes {0} [built]
    aurelia module async?lazy&name=masterdata!masterdata/Masterdata [infrastructure/Routes] ./app/infrastructure/Routes.ts

[masterdata/Masterdata] ./app/masterdata/Masterdata.ts 2.41 kB {0} [built]
    aurelia module masterdata/Masterdata.ts [162] ./~/aurelia-webpack-plugin/dist/aurelia-entry.js
    cjs require !!../../node_modules/cache-bust-loader/index.js?name=bust&value=!../../node_modules/awesome-typescript-loader/dist/entry.js!./Masterdata.ts [async!masterdata/Masterdata] ./~/bundle-loader?lazy&name=masterdata!./app/masterdata/Masterdata.ts 3:5-155
```

This are the only two places where `masterdata/Masterdata` is listed as requirement from another modules. This is a "top-level" module and has no imports in the whole project.

The route config for this is:
```
        {
            route: 'masterdata',
            name: 'masterdata',
            moduleId: PLATFORM.moduleName("masterdata/Masterdata", "masterdata"),
            title: "view.masterdata.title",
            nav: true,
            auth: true,
            iconClass: "fa-database"
        },
```

**Comment by jods4** [comment]
OK I see.
You can't use code splitting when using `includeAll: true` option. 

This is a shortcut that allows you to not use `moduleName` internally in your project and basically takes all your files and puts them into a single bundle. 
It has several limitations regarding optimizations, not being able to code-split your app is one of them.

Reading the docs again I think I need to stress out the limitations a bit more.

**Comment by code-chris** [comment]
Yes, the splitting works now, if I remove `includeAll`. But now I get an error for TypeScript-Files:
```
ERROR in ./app/main.ts
Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (M:\other\test-app\client\node_modules\webpack\lib\NormalModule.js:201:46)
    at M:\other\test-app\client\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (M:\other\test-app\client\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (M:\other\test-app\client\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at M:\other\test-app\client\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at context.callback (M:\other\test-app\client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at M:\other\test-app\client\node_modules\awesome-typescript-loader\src\index.ts:106:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./~/aurelia-webpack-plugin/dist/aurelia-entry.js
 @ multi aurelia-webpack-plugin/dist/aurelia-entry aurelia-polyfills aurelia-loader-webpack aurelia-bootstrapper
```

If I replace `awesome-typescript-loader` with the `ts-loader` it works. Is this a bug in at-loader or with the aurelia plugin?

**Comment by jods4** [comment]
Not sure what goes on here. 
At first glance doesn't look related to Aurelia plugin, might be a problem with at-loader.

**Comment by code-chris** [comment]
ok
