### ISSUE TITLE
ModuleDependenciesPlugin does not create chunks

### ISSUE THREAD

**Issue by MrHayato** [aurelia/webpack-plugin#111]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.1

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 2.3.1

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When using ModuleDependenciesPlugin, the `chunk` option does nothing.

**Expected/desired behavior:**

* **What is the expected behavior?**
As per the wiki docs, you should be able to specify a chunk by doing `{ name: moduleName, chunk: chunkName }`. However, this doesn't create a chunk.
This can be worked around, if I manually specify the name using:
```
{ name: `async?lazy&name=${chunkName}!${moduleName}` }
```

* **What is the motivation / use case for changing the behavior?**
I want to be able to create module chunks using ModuleDependenciesPlugin, similar to how PLATFORM.moduleName works.

**Comment by jods4** [comment]
You are correct, the documentation uses `chunk` as an example option for `ModuleDependenciesPlugin` but it's actually the only one the doesn't work, because it's treated differently internally.

I think I should be able to make this work, will do for RC 3.

**Comment by jods4** [comment]
Thanks for submitting this. I have made `chunk` work consistently between `moduleName` and `ModuleDependenciesPlugin`.

When RC3 is published, code in the issue will work as expected.
