### ISSUE TITLE
Activate methods are not been called in the same order as they been placed inside the HTML.

### ISSUE THREAD

**Issue by Alaboudi1** [aurelia/webpack-plugin#114]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.2
* **Operating System:**
Windows 10
* **Node Version:**
v7.2.1

* **NPM Version:**
5.0.3

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
all 
* **Language:**
all
**Current behavior:**
Disclaimer: I am not sure if this inconsistent behavior is a bug or misuse of the framework from my side.

When using compose element inside a project that uses Webpack, an inconsistent behavior happens. The invocation of activate method in the view-model is not in order. That is, if you have an array of elements and you pass each element of that array to a view-model, there is no grantee that the activate method for the first compose element is going to be called before the others.
For example:
if you have app.js and app.html as follows:

```
export class App {
    constructor(){
      this.numbers = [1,2,3,4,5,6,7,8,9,10];
    }
}

```

```
<div repeat.for="number of numbers">
  ${number}
<compose view-model="comp" model.bind="number"></compose>
```
 and comp.js as below
```
export class comp {
activate(number) {
  console.log(number);
}
}
``` 
 you would expect that the html output render from app.html to match the console logs from activate methods, but the is not the case. First, I thought I was using the compose element the wrong way until I tried the same code with System.js and the two outputs match.  [Here is a demo with System.js ](https://gist.run/?id=ab21fb3969531f875beac8ed95aba843).

Other thing I notice that when I use require tag 
`<require from='comp'></require>`
The bug is fixed. But this is not required for the System.js solution! 
   
[Here is a live demo of the bug](https://alaboudi1.github.io/aurelia-webpack/).  
[Here is the a very simple example for the bug.](https://github.com/Alaboudi1/aurelia-webpack)

* **What is the expected behavior?**
I am expecting that the activate methods are called in the same render order even without the require tag (to match the System.js behavior) . 

* **What is the motivation / use case for changing the behavior?**
This bug makes the $last $first in repeat.for useless.

**Comment by jods4** [comment]
I am not sure if `repeat.for` + `<compose>` do provide such a guarantee (that callbacks happen in markup order). If they do, you should open a bug in `aurelia/templating-resources`, where `<compose>` is defined.

As far as Webpack goes, it sits well under that and has no specific knowledge of `<compose>` or any HTML templating for that matter.

What I suspect happens is that `<compose>` works asynchronously -- [starting here](https://github.com/aurelia/templating-resources/blob/master/src/compose.js#L186) -- one of the first thing it has to do is load the ViewModel class and it queues one load for each element.
Those loads get all satisfied at the same time by `aurelia-loader` / Webpack but the callbacks are probably not called in the same order as with SystemJS.

And that makes me think the bug might be in `aurelia-loader-webpack` or `aurelia-loader` if it's supposed to enforce callback order but does not?

**Comment by EisenbergEffect** [comment]
We don't guarantee any timing of events with completely dynamic composition.

**Comment by Alaboudi1** [comment]
@jods4 & @EisenbergEffect  thanks for the clarification. Then, is there an elegant way to check if all activate methods have been called? I used $last when I was using System.js and the bug has not appeared, but when I switched to webpack, that bug shows up almost every time.
