### ISSUE TITLE
Direct inclusion of a known Aurelia component still results in webpack not finding it.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/webpack-plugin#117]
I am trying to implement bundling of our application at present. Using aurelia-webpack-plugin 2.0.0-rc.2 and webpack 2.6.1.

The aurelia-webpack-plugin goes to quite a bit of effort to determine dependencies for a module, for example by searching through HTML files for <require> and <compose> elements, and looking through JS files (or an AST) for PLATFORM.moduleName expressions. In addition, when a view-model is discovered via these approaches, a convention-based check occurs to pick up the corresponding HTML file.

I am raising this issue partly for guidance and partly to question whether my situation might be a reasonable use-case to consider an improvement to the plugin.

In our implementation we have roughly 100 views at present. For example, "app-assetlist.ts" contains our view model for Asset Maintenance. There is an associated app-assetlist.html file. Each of our view-models exposes a "DialogDefinition" object, one property of which is the "Route" that will be used to register that dialog.

We do not manually configure our Aurelia route table for the most part. Instead we have a factory concept where all the views are registered, and we iterate over the factory items to collect a bunch of routes to feed into the route table. This happens at startup.

Key point: our factory, at present, simply imports all the needed modules to register them. Hence, webpack knows of all the modules existence and builds successfully. But it won't run.

When the application runs, many of these modules cannot be found by Aurelia, even though they are _in the bundle_. The reason is that the module has been referenced via an import statement, and not by PLATFORM.moduleName, and hence the aurelia-webpack-plugin does not set up the string-based module-id for that webpack module, leaving that module with an integer module id.

The exception to the above rule is when the module has a corresponding .html view file (based on convention-based naming), then the view is correctly included in the bundle with a string-based module id (instead of an integer). It took a while to find the correlation of why some module-ids were strings and some were integers.

Unfortunately for our project, a large proportion of our view-models have "templates" that are dynamically generated purely through code, based on configuration data coming from server, and therefore *they have no associated html template files*. Most of our views are actually constructed dynamically via hooking into getViewStrategy( ).

The net result is this:

import {x} where x has an associated .html template file - X is bundled correctly.
import {y} where y has no associated html template file - Y is not bundled correctly (integer module id).

So, the focus of this issue is not on finding the dependency, but recognising that the module in question *is an Aurelia view-model* and dealing with it correctly.

Are there any other markers/characteristics that the aurelia-webpack-plugin can use to identify an Aurelia view-model and thus treat it *correctly*.

Otherwise, it would appear I am facing the prospect of having to refer to these modules by PLATFORM.moduleName, not to get them included into the bundle, but simply because the current form-of-reference to the module is insufficient to get them _bundled in the correct manner_. And yet, if these views had an associated html file, they would have been bundled correctly.

I know I can possibly use the includeAll option, but I'm not really keen to go down this path.

Possible ideas might be any of:
1. Modules with a dependency on aurelia-xxx are considered "aurelia modules" and bundled by name.
2. Classes containing the method getViewStrategy are considered "Aurelia modules" and bundled by name (not even sure if this would satisfy our use-case as our getViewStrategy sits in a base-class, which I expect is beyond the scope/reach of the AST).

Feedback and recommendations appreciated.

**Comment by jods4** [comment]
Your analysis is correct.

To summarize it: Webpack needs to treat modules requested by `aurelia-loader` at runtime in a special way. Aurelia Webpack plugin provides several ways to indicate that a module will be loaded by Aurelia, first and foremost `PLATFORM.moduleName()`.

This implies a lot of runtime behaviour must be discovered at build time and JS being JS, this can be hard. Unfortunately it's not very friendly with dynamic runtime constructions, such as building the route table like you do.

The cleanest way is likely to build a plugin that provides knowledge of what will happen at runtime to Webpack. I understand this can seem too hardcore for most people.

There are various generic tools in `aurelia-webpack-plugin` that you can try to leverage:
- Even though you build your route table dynamically, I imagine the `moduleId` value has to be found somewhere in the code base, right? That would be a good place to wrap it with `moduleName`.
- You can use `ModuleDependenciesPlugin` and list the "route modules" that you import. Webpack config being javascript, maybe you can script that list based on some pattern?
- Speaking of patterns you can use `GlobDependenciesPlugin` to discover all your "route modules" based on a glob, if you have a supporting convention.

`includeAll` is not a good idea for large projects as it leads to larger builds, prevents several Webpack optimizations and prevents code splitting. It's really meant as an easy migration path or for small projects/demos.
