### ISSUE TITLE
Can't import json files in 'production' mode

### ISSUE THREAD

**Issue by m0ngr31** [aurelia/webpack-plugin#124]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.2

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 16.04)

* **Node Version:**
7.10.1

* **NPM Version:**
5.3.0

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Trying to import a json file in one of my js files, and it works when I'm using webpack-dev-server, but not when I'm just doing a build.

```
ERROR in ./src/apps/cms/routes/live-events/list.js
Module not found: Error: Can't resolve './test.css.json' in '/home/joe/projects/cms/src/apps/cms/routes/live-events'
```

* **What is the expected behavior?**
To import on both dev and production

**Comment by jods4** [comment]
Could you please add some details?

In particular: 
- How is this related to the Aurelia plugin? 
At first glance from your description this looks like a generic Webpack problem that doesn't involve Aurelia. In that case, Webpack github issues, Webpack gitter channel or stackoverflow might be better venues to seek help, 
- If this is linked to Aurelia, how (code) are you trying to load `test.css.json`?

**Comment by m0ngr31** [comment]
It turns out that I'm just an idiot. On webpack-dev-server, it would generate the .json file just like it would in prod mode, but dev would fail as well, but then see the json file as a new file and it would recompile, making it able to import the second time around.

I changed my implementation so I have a working solution now. Sorry for the confusion.

**Comment by jods4** [comment]
Glad you sorted it out.
