### ISSUE TITLE
Incompatible with ts-loader transpileOnly mode.

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/webpack-plugin#126]
**I'm submitting a bug report**

* **Library Version:**
aurelia-webpack-plugin@2.0.0-rc.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.0.0
* **NPM Version:**
5.2.0

* **JSPM OR Webpack AND Version**
webpack@3.6.0

* **Browser:**
all

* **Language:**
Typescript

**Current behavior:**
Using Aurelia/Typescript with the `ts-loader` option `transpileOnly: true` set will will result in errors similiar to the Aurelia PAL not properly loading. In my specific case, a custom element isn't properly getting it's Element injected.

I'm using transpileOnly (and alternatively happy pack mode) to speed up builds a little.

**Comment by jods4** [comment]
My first instinct would be to redirect this to `ts-loader` folks...

`transpileOnly` is supposed to speed up compilation by not doing type checking, but the resulting JS code should be exactly the same. Turning this on or off should have no visible effect (other than muting TS errors).

If you sift through issues, it wouldn't be the first time `transpileOnly` has bugs that changes the output.

Aurelia plugins have no code specific to `ts-loader`, you could use raw JS, Coffeescript or whatever you like, as long as the output of your loader is good JS.

**Comment by Alexander-Taran** [comment]
@bigopon let's close this
