### ISSUE TITLE
Html for component doesn't included in the bundle

### ISSUE THREAD

**Issue by Boychenko** [aurelia/webpack-plugin#128]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**
2.0.0-rc.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.1

* **NPM Version:**
5.3.0

* **JSPM OR Webpack AND Version**
webpack 3.7.1

* **Browser:**
all
* **Language:**
TypeScript 2.4.1

**Current behavior:**
Took this sample `https://github.com/jods4/aurelia-webpack-build/tree/master/demos/02-Traced_deps`
run `npm i`
run `webpack`
run `npm run web`
Got
```
bundle.js:26193 Uncaught (in promise) Error: Unable to find module with ID: app.html
    at WebpackLoader.<anonymous> (bundle.js:26193)
    at step (bundle.js:26042)
    at Object.next (bundle.js:26023)
    at bundle.js:26017
    at new Promise (<anonymous>)
    at 77.__awaiter (bundle.js:26013)
    at WebpackLoader.77.WebpackLoader._import (bundle.js:26158)
    at WebpackLoader.<anonymous> (bundle.js:26258)
    at step (bundle.js:26042)
    at Object.next (bundle.js:26023)
```

**Expected/desired behavior:**

* **What is the expected behavior?**
Application works

* **What is the motivation / use case for changing the behavior?**
It should work

I made some investigation.
`webpack --display-modules` gives
windows:
```
  [39] Samples/demos/02-Traced_deps/node_modules/style-loader/lib/urls.js 3.01 kB {0} [built]
[app] Samples/demos/02-Traced_deps/src/app.ts 196 bytes {0} [built]
[aurelia-event-aggregator] Samples/demos/02-Traced_deps/node_modules/aurelia-event-aggregator/dist/native-modules/aurelia-event-aggregator.js 2.89 kB {0} [built]
```
ubuntu:
```
 [40] ./node_modules/style-loader/lib/urls.js 3.01 kB {0} [built]
[app] ./src/app.ts 188 bytes {0} [built]
[app.html] ./src/app.html 309 bytes {0} [built]
[aurelia-event-aggregator] ./node_modules/aurelia-event-aggregator/dist/native-modules/aurelia-event-aggregator.js 2.89 kB {0} [built]
```
It's seems to me that it's path issue. Probably this `"./"` causes the problem on this line https://github.com/aurelia/webpack-plugin/blob/e7935cf81f8f710f340865af9c557c263068db01/src/ConventionDependenciesPlugin.ts#L37 but I'm not sure.

**Comment by jods4** [comment]
If I understand you correctly it works on Ubuntu but not on Windows? So it would be some kind of path and slashes issue?

That's very weird because I am on Windows and it works for me.
I'm using Yarn as package manager and I doing:
```
yarn
yarn run web 
```
Does work as expected???

It would be nice to find out what's different on your machine. 
I can only assume that either:
- `npm` got you some lib with a different version than me. Could you try to see if it works with Yarn? The nice thing about Yarn is that the specific version of every library I use are locked down inside `yarn.lock`, so you'd have _exactly_ the same `node_modules` as me.
- Version of Node makes a difference?! I'm on Node 8.5.0 if you can afford to try that.
- Some weird OS config somewhere is different? I'm on Win 10 as well.

**Comment by Boychenko** [comment]
Hi @jods4 
Because I've tested this flow on 5-6 windows machines and it works as expected everywhere (win7, win10). Apart from my laptop.
I've tried to remove node completely and install 8.7 and 6.11.4.
Finally, I got this work on "Bash on Ubuntu on Windows"

`yarn` gives exactly same result

So, I'm thinking about this "Some weird OS config somewhere is different?".
Can you give me a hint what settings I can check?
I'm going to do some debugging during a weekend.

**Comment by jods4** [comment]
OK then, glad you found out!

Symlinks should work (that's how I work and test new versions of aurelia modules before they get published) if you set the environment variable `NODE_PRESERVE_SYMLINKS`

**Comment by Boychenko** [comment]
@jods4 
I think it'd be really cool to have this info in the somewhere in the wiki. 
Anyone can run into this issue since because of this fresh app generated via `au new` with webpack selected not working with symlink the path.
