### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by eric-914** [aurelia/webpack-plugin#135]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.0

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 3.10.0

* **Browser:**
Chrome 62.0.3202.94

* **Language:**
TypeScript 2.6.2

**Current behavior:**
When I run Webpack through gulp, I get the following message when my AureliaPlugin is included in webpack's config file:

`(node:5920) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'default' of undefined`

It does not appear that AureliaPlugin has executed, as my output bundle is significantly smaller.  This warning does not appear if I run Webpack directly.

**Expected/desired behavior:**

AureliaPlugin behavior should be consistent in either invocation.

**Additional:**
My AureliaPlugin usage:
```
        new AureliaPlugin({
            dist: "native-modules",
            includeSubModules: [
                { moduleId: "aurelia-dialog" },
                { moduleId: "aurelia-validation" }
            ]
        })
```

My gulp task:

```
var gulp = require("gulp");
var webpack = require("webpack");

var config = require("../../webpack.dev.js");

gulp.task("webpack",
    (done) => {
        var onBuild =
            function(err, stats) {
                if (err) {
                    console.log(`Error: ${err}`);
                } else {
                    Object.keys(stats.compilation.assets).forEach(function(key) {
                        console.log(`Webpack: output ${key}`);
                    });
                }
            }

        webpack(config, onBuild);

        done();
    }
);
```

My invocation of webpack via gulp:
`npm run gulp webpack`

I originally had this problem with another webpack plugin, but turns out I didn't need it.  All remaining webpack plugins (5) do not have this warning.

**Comment by jods4** [comment]
Before any further action: your invocation of `done` is clearly incorrect. It should happen when the task completes, i.e. inside `onBuild`.

**Comment by eric-914** [comment]
Yeah, I noticed that as well the next day.  It didn't change anything regarding this issue though.  This isn't high priority to me, I've moved on to stop using the gulp steps.  But I thought it still should be noted that it occurs.

**Comment by jods4** [comment]
I don't have time to debug this, as long as Webpack CLI works it's not a critical issue... Not sure why the Webpack JS API would behave any different.

The error _Cannot read property 'default' of undefined_ smells like a `import X from "abc"` that failed to resolve properly.

**Comment by Alexander-Taran** [comment]
@eric-914 have you tried it with webpack4 and new version of plugin?
I don't see a way that plugin would be called differently.
If you look at CLI source - it calls webpack directly.
Your gulp task probably tries to do the same.

You can compare how it's implemented and figure out where mismatch is.

**Comment by jauniuse** [comment]
Having the same issue.

**Comment by jods4** [comment]
Can someone post a stacktrace?

**Comment by Alexander-Taran** [comment]
I think this one https://github.com/aurelia/dialog/issues/283#issuecomment-383058460 is the same. So workaround applies.

**Comment by rbmanian75** [comment]
I am also facing the same issue. Any Help would be appreciated

**Comment by Alexander-Taran** [comment]
@3cp maybe should be closed (-:

**Comment by 3cp** [comment]
cc @bigopon

**Comment by bigopon** [comment]
This probably shouldn't be an issue in the latest version of the plugin. If you do face it, please open a new issue.
