### ISSUE TITLE
Webpack docs - update needed

### ISSUE THREAD

**Issue by domenkogler** [aurelia/webpack-plugin#147]
**I'm submitting a feature request**

[Duplicate Modules in Multiple Bundles](https://aurelia.io/docs/build-systems/webpack/bundling#duplicate-modules-in-multiple-bundles) describes use of `CommonsChunkPlugin`, but it is [depreciated after Webpack v4 release](https://webpack.js.org/plugins/split-chunks-plugin/) in favor of `optimization.splitChunks`.

**Comment by jods4** [comment]
Thanks for the notice. 
I believe the hub docs still refer to our previous v1 webpack plugin and as such are severly outdated.
In the meantime the wiki here is your best source of information when using v2+.

@EisenbergEffect should we create an issue in aurelia/documentation?

**Comment by EisenbergEffect** [comment]
Yes, please open an issue for this documentation task. All I need is a PR to update the markdown files with correct content. I can publish updated docs as soon as I have that. The existing docs are here: https://github.com/aurelia/framework/tree/master/doc/article/en-US

**Comment by jods4** [comment]
I just linked this with aurelia/documentation#348.

I am closing this issue as this repo is really about the plugin itself, not docs.
@domenkogler feel free to comment in that other issue.
