### ISSUE TITLE
No PLATFORM.Loader is defined

### ISSUE THREAD

**Issue by jauniuse** [aurelia/webpack-plugin#149]
**I'm submitting a bug report**

* **Library Version:**
3.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.1

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 4.4.1

* **Browser:**
all

* **Language:**
TypeScript 2.6.1

**Current behavior:**

`aurelia-bootstrapper` logs error in console: `No PLATFORM.Loader is defined and there is neither a System API (ES6) or a Require API (AMD) globally available to load your app.` when using aurelia-webpack plugin. Application works fine, it's just this error. This issue was brought up in https://github.com/aurelia/bootstrapper-webpack/issues/16

**Comment by jauniuse** [comment]
closing this since I'm not using `aurelia-bootstrapper-webpack` and will get back here if issue persists later on when using `aurelia-bootstrapper-webpack`

**Comment by jods4** [comment]
To clarify: are you using `aurelia-bootstrapper-webpack` (you shouldn't)?

We'll need more information (e.g. a repro) to do anything with this issue.
Basic scenario works for most people.

**Comment by jauniuse** [comment]
@jods4, no, I'm using `aurelia-bootstrapper`. I will get back with some example repo.

**Comment by jauniuse** [comment]
It turns out a mistake in my `webpack.config.js` was causing error.

Before:

```js
 entry: {
    main: ['aurelia-bootstrapper', ...],
    vendors: ['aurelia-bootstrapper', ...]
 }
```

Removing 'aurelia-boostrapper' from vendors fixed the issue
