### ISSUE TITLE
Dialogs are not added to the aurelia-metadata Origin?

### ISSUE THREAD

**Issue by sickboy** [aurelia/webpack-plugin#16]
~~~
import {Index as SettingsIndex} from '../../settings/index';
this.dialog.open({viewModel: SettingsIndex, model: model})
~~~

Does not work, unless first:

~~~
import {Origin} from 'aurelia-metadata';
Origin.set(SettingsIndex, {moduleId: "features/settings/index", moduleMember: "Index"});
~~~

**Comment by EisenbergEffect** [comment]
It worked fine for me with the latest today. Can you provide a simple project that reproduces the issue?

**Comment by Vheissu** [comment]
This does not appear to be an issue that has occurred for anyone else since this was posted. Also taking into account in April when this was posted, the plugin was in a very alpha/experimental stage.

**Comment by sickboy** [comment]
@EisenbergEffecty im still running into this with the very latest code. Will try to get a repro project going..

**Comment by EisenbergEffect** [comment]
I believe this is an issue with the webpack loader not being able to map module ids correctly like system.js or require.js. If that's the case, it's being looked into. As a workaround, use a module id instead of a type for opening dialogs.
