### ISSUE TITLE
Document options

### ISSUE THREAD

**Issue by benstevens48** [aurelia/webpack-plugin#161]
It would be useful to document the options, especially the 'aureliaApp' option. I'm not using the CLI and am doing manual boostrapping, so I kew there was no way that setting my webpack entry to 'aurelia-bootrapper' could possibly work. Eventually from looking at the code of this plugin, I found the answer was as simple as setting the 'aureliaApp' option to the same as my webpack entry.

**Comment by jods4** [comment]
There is documentation in the Wiki section of this wiki.
[This page](https://github.com/aurelia/webpack-plugin/wiki/AureliaPlugin-options) describes all plugin options.
Apologies for not being easy to discover.

**Comment by benstevens48** [comment]
Ok, thanks, that's very helpful. Perhaps you could add a link to this page from the readme?

**Comment by jods4** [comment]
@benstevens48 no problem, it's done.
