### ISSUE TITLE
Publish new version on NPM

### ISSUE THREAD

**Issue by silbinarywolf** [aurelia/webpack-plugin#162]
@EisenbergEffect Can you please publish a new version on NPM?

As I mentioned [here](https://github.com/aurelia/webpack-plugin/issues/157#issuecomment-487791848), my personal opinion is that it should be bumped to 4.0.0, however @jods4 thinks jumping to 3.1.0 should be fine.

Ultimately it's up to you folks what you decide to do!

**Comment by EisenbergEffect** [comment]
I've added it to my release todo list for this week. I'll get it out within the next few days.

**Comment by silbinarywolf** [comment]
Awesome, thanks for the quick reply :)

**Comment by EisenbergEffect** [comment]
Per community request, published at 4.0.0.
