### ISSUE TITLE
Remove dependency on deprecated/unmaintained bundle-loader

### ISSUE THREAD

**Issue by rmja** [aurelia/webpack-plugin#167]
**I'm submitting a feature request**

* **Library Version:**
master

**Current behavior:**
The plugin depends on [bundle-loader](https://github.com/webpack-contrib/bundle-loader) as a runtime dependency, but that library is currently archived on GitHub and is no longer maintained. It [has issues that have not been addressed for years](https://github.com/webpack-contrib/bundle-loader/pull/75), so it would be really nice if the plugin did not depend on its existence.

**Expected/desired behavior:**
Avoid using the deprecated bundle-loader dependency, and maybe replace its use with dynamic imports.

**Comment by rmja** [comment]
I don't think that i know the internals of webpack and this plugin good enough to do this...

**Comment by MaximBalaganskiy** [comment]
bump!
there's a critical vulnerability in bundle-loader -> loader-utils@1.4.1

**Comment by Alexander-Taran** [comment]
@bigopon ping

**Comment by Rtalos** [comment]
Is there an ETA on a fix for this? Our SCA tool is giving us warnings about this.

**Comment by bigopon** [comment]
I'll get on this soon.

**Comment by bigopon** [comment]
I'm not aware of a replacement for bundle-loader, I think the simplest fix which I'll apply is to have a local copy in the dist of tis plugin and use it instead, then remove the dep on `bundle-loader`.

**Comment by rmja** [comment]
@bigopon if you do that, then please add this fix: https://github.com/webpack-contrib/bundle-loader/pull/75

**Comment by bigopon** [comment]
v `5.0.5` has been published for the fix of this issue. Thanks everyone.

@rmja we can't just change it, can you help create a fail test case? Or if you want, can bundle the failing test case with your fix in a PR.
