### ISSUE TITLE
Aurelia Validation (System is not defined)

### ISSUE THREAD

**Issue by avizcaino-newuibcn** [aurelia/webpack-plugin#17]
Hi,

I'm wondering if anyone has faced the same problem integrating aurelia-validation with the webpack solution...

I'm trying to integrate aurelia-validation plugin and the compilation/bundle is working fine but when I run the app, it gets stuck in the splash screen with a `System is not defined` error in the console...

**Comment by EisenbergEffect** [comment]
@pwkad We really need to get this fixed asap.

**Comment by praga** [comment]
Im having the same issue as well, is there a quick fix for this or do we have to wait for an update?

**Comment by avizcaino-newuibcn** [comment]
Seems it is solved with the last aurelia-validation update https://github.com/aurelia/validation/pull/236
