### ISSUE TITLE
No view model found in module

### ISSUE THREAD

**Issue by elitastic** [aurelia/webpack-plugin#171]
**I'm submitting a bug report**

* **Library Version:** version supporting webpack 5 (directly taken from repo dist)

**Please tell us about your environment:**
* **Operating System:** Windows 10
* **Node Version:** 12.20.0
* **NPM Version:** 6.14.8
* **JSPM OR Webpack AND Version** webpack 5.37.1
* **Browser:** Brave 1.25.68
* **Language:** TypeScript 4.3.2

**Current behavior:**
Everything working fine in modes "development" and "none" of webpack. When changing mode to production (also when removing mode option) I get the following error:

No view model found in module "path/to/my-module". It does not matter whether it is relative or absolute path, it does not work in either case.

**Expected/desired behavior:**
Would expect to work in development *and* production mode.

**Comment by bigopon** [comment]
@elitastic can you help with a small repro? Or at least how the structure looks like? Another Q: is there any signal to retrieve such module like `PLATFORM.moduleName`?
