### ISSUE TITLE
Does not work due to missing Array.prototype.find()

### ISSUE THREAD

**Issue by kuechlerm** [aurelia/webpack-plugin#19]
Array.prototype.find() is used [here](https://github.com/aurelia/webpack-plugin/blob/master/index.js#L102), but that seems to be not available on node 0.12. Is it possible to require a polyfill or can I work around that in another way?
Thanks.

**Comment by jsobell** [comment]
It's already in the aurelia-polyfills: [https://github.com/aurelia/polyfills/blob/master/src/array.js#L46](https://github.com/aurelia/polyfills/blob/master/src/array.js#L46)
Make sure you include this module in your build.

**Comment by Gheoan** [comment]
@jsobell `webpack-plugin` runs on the server (nodejs) not in the browser. `aurelia-polyfills` is a browser package.

**Comment by Vheissu** [comment]
I think this issue can now be closed @EisenbergEffect the line in question doesn't exist in the new version.

**Comment by niieani** [comment]
I'd just like to note that webpack-plugin only supports Node >= 4.0.
