### ISSUE TITLE
Webpack 5 caching not working (No serializer registered for IncludeDependency/AureliaDependency)

### ISSUE THREAD

**Issue by glen-84** [aurelia/webpack-plugin#199]
**I'm submitting a bug report**

* **Library Version:**
5.0.3

**Please tell us about your environment:**
* **Operating System:**
Debian

* **Node Version:**
v14.18.2

* **NPM Version:**
6.14.15

* **JSPM OR Webpack AND Version**
webpack: 5.65.0
webpack-cli: 4.9.1
webpack-dev-server 4.6.0

* **Browser:**
n/a

* **Language:**
TypeScript 4.5.3

**Current behavior:**

Running a build with the following webpack cache configuration:

```js
        cache: {
            type: "filesystem",
            buildDependencies: {
                config: [__filename]
            }
        }
```

I get many warnings like:

```
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/home/glen/development-environment/Projects/Crew Panel/node_modules/ts-loader/index.js??ruleSet[1].rules[6].use[0]!/home/glen/development-environment/Projects/Crew Panel/src/app/resources/elements/gg-sort-link.ts': No serializer registered for IncludeDependency
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 16 items } -> IncludeDependency
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/home/glen/development-environment/Projects/Crew Panel/node_modules/ts-loader/index.js??ruleSet[1].rules[6].use[0]!/home/glen/development-environment/Projects/Crew Panel/src/app/view-models/app.ts': No serializer registered for AureliaDependency
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 182 items } -> AureliaDependency
```

**Expected/desired behavior:**

* **What is the expected behavior?**

Support for webpack 5 caching / no warnings.

* **What is the motivation / use case for changing the behavior?**

Performance / clean output.

**Comment by elitastic** [comment]
I've exactly the same problem!

**Comment by elitastic** [comment]
https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md#serialization

Is this part missing? Do we have to register serialization handlers for au components?

**Comment by bigopon** [comment]
@elitastic yes it is missing. I wasn't aware of this necessity while migrating. Haven't been able to come back to this yet.
