### ISSUE TITLE
Processing files from package.json

### ISSUE THREAD

**Issue by mr47** [aurelia/webpack-plugin#25]
Problem with process `package.json`.
`aurelia-webpack-plugin` don't care about default loader for `.js` files so all files that in `node_modules` are created inside a `contextMap` (but some can be a `node-sass` module as example.)

Its related to #12 

Simple solution for now is exclude an `node_modules` from loading by `aurelia-webpack-plugin` (because default webpack loader for `.js` files don't care about `node_modules`)
like so:

```js
 module: {
    loaders: [
      //...
      { test: /\.ts$/, loader: 'ts-loader'}, // if you are using typescript
      { test: /\.js$/, loader: 'raw', exclude: /node_modules/ }
     //...
   ]
}
```

I think need add an option `exclude`, so it can exclude a `node_modules` or other stuff from `contextMap` and don't proceed it.

**Comment by Vheissu** [comment]
I believe this issue is now redundant given the plugin has been redeveloped and no such issues have been reported since.
