### ISSUE TITLE
Cannot find module 'aurelia-framework'

### ISSUE THREAD

**Issue by genericuser-me** [aurelia/webpack-plugin#27]
I was using aurelia with jspm. Now trying to move jspm to webpack. 
Used the skeleton to create the project. However, when I run npm run dev, it gives me error : 

Cannot find module 'aurelia-framework'

and same for all aurelia dependencies.

Can anyone please help!

**Comment by mirronelli** [comment]
are you refering to the Typescript skeleton?
if so, you need to run the following on the command prompt first before running the dev server
npm install
typings install

**Comment by doktordirk** [comment]
i'm not using typescript and have the same issue

**Comment by doktordirk** [comment]
i fixed it with going back to 1.*
@EisenbergEffect seems broken

**Comment by hwolf** [comment]
I have the same issue with the skeleton-es2016-webpack app.

If I run npm run dev, the browser console shows
`Uncaught Error: Cannot find module './aurelia-framework'.`

**Comment by EisenbergEffect** [comment]
We are working on new releases for the skeletons now. Releasing soon.

**Comment by doktordirk** [comment]
Meanwhile, change in your package.json to
"aurelia-webpack-plugin": "1.0.0-beta.1.0.4" (no ^there) and then `npm prune && npm i`
