### ISSUE TITLE
NPM linked packages sometimes do not get resolved properly

### ISSUE THREAD

**Issue by MrHayato** [aurelia/webpack-plugin#31]
This is kind of a continuation of my post from #30, but I found the reason for my problem and it had to do with npm links. Here is the structure of my project:

- Core
  - dependencies: aurelia-framework, aurelia-binding, etc.
- Bootstrapper
  - dependencies: Core
- AppFoo
  - dependencies: Bootstrapper
- AppBar
  - dependencies: Bootstrapper
- Hub
  - dependencies: AppFoo, AppBar

The Hub application loads a bunch of mini-apps, and each mini-app gets bootstrapped with Aurelia via the bootstrapper. This allows us to also run each mini-app directly.

In my use case, I was working in Hub, and because I'm migrating all our projects to use beta 2 of aurelia-webpack-plugin, I have all my projects npm linked (including Appbar, AppFoo, Bootstrapper, Core) in my Hub application with the appropriate aurelia.build.resources set. However, the aurelia-webpack-plugin is not resolving some resources properly. From what I can tell, instead of resolving Core in my Hub/node_modules folder, it's trying to resolve it from within the `AppFoo/node_modules/Bootstrapper/node_modules/Core` folder. This is failing at some point, and causes my app to error out with `Cannot find module ./blah`.

Once I deleted every node_modules folder from AppFoo, AppBar, etc then the dependencies now resolve all the way down the hierarchy, although with the wrong dependency paths, which is most likely the Windows issue everyone else is having.

**Comment by niieani** [comment]
I wouldn't count on proper module resolution on Windows yet. Let's fix the Windows path issue and then we can test if this is still an issue.

**Comment by MrHayato** [comment]
This is actually an issue with webpack v2 and not the plugin. I'm getting other issues but I'll log a new issue for that.
