### ISSUE TITLE
Infinite Loop Error Relating To "compose.js" In Console

### ISSUE THREAD

**Issue by Vheissu** [aurelia/webpack-plugin#34]
I have upgraded to the latest releases which fix the Windows path issues, however, I am encountering an issue where I am seeing this infinite loop in my PowerShell window with the following:

```
<aurelia-templating-resources> [package.json] required "./aurelia-templating-resources/compose.js" from "node_modules/aurelia-templating-resources/dist/es2015/compose.js".
<aurelia-templating-resources> [package.json] required "./aurelia-templating-resources/compose" from "node_modules/aurelia-templating-resources/dist/es2015/compose.js".
<aurelia-templating-resources> [package.json] required "./aurelia-templating-resources/dist/es2015/compose" from "node_modules/aurelia-templating-resources/dist/es2015/comp
ose.js".
```

I let it go for 10 minutes thinking it might correct itself, but it keeps displaying this over and over again.

**Comment by icanhasjonas** [comment]
Same on OSX

`git clone git@github.com:aurelia/skeleton-navigation.git`

`npm install`
+> `typescript`

`npm run server`

`node --version` => `v5.10.1`
`npm --version` => `3.8.3`

**Comment by niieani** [comment]
Closed in: https://github.com/aurelia/webpack-plugin/commit/215f8ed1fd7cfc5e4483e63443ed8067ef39e8a5
Will publish soon.
