### ISSUE TITLE
Error while typings install "Attempted to compile "aurelia-dependency-injection" as a global module, but it looks like an external module"

### ISSUE THREAD

**Issue by genericuser-me** [aurelia/webpack-plugin#37]
Hi,
while running typings install I get the following error:

```
C:\prj\Project\myapp>typings install
typings ERR! message Attempted to compile "aurelia-dependency-injection" as a global module, but it looks like an external module. Did you want to enable the global flag?

typings ERR! cwd C:\prj\Project\myapp
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v6.2.0
typings ERR! typings -v 1.2.0

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```

here is my typings.json:

```
{
  "name": "aurelia-skeleton-navigation-typescript-webpack",
  "version": false,
  "dependencies": {
    "moment": "npm:moment/moment.d.ts"
  },
  "globalDependencies": {
     "aurelia-binding": "npm:aurelia-binding/dist/aurelia-binding.d.ts",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts",
     "aurelia-event-aggregator": "npm:aurelia-event-aggregator/dist//aurelia-event-aggregator.d.ts",
    "aurelia-fetch-client": "npm:aurelia-fetch-client/dist/aurelia-fetch-client.d.ts",
    "aurelia-framework": "npm:aurelia-framework/dist/aurelia-framework.d.ts",
    "aurelia-history": "npm:aurelia-history/dist/aurelia-history.d.ts",
    "aurelia-history-browser": "npm:aurelia-history-browser/dist/aurelia-history-browser.d.ts",
    "aurelia-loader": "npm:aurelia-loader/dist/aurelia-loader.d.ts",
    "aurelia-loader-webpack": "npm:aurelia-loader-webpack/dist/aurelia-loader-webpack.d.ts",
    "aurelia-logging": "npm:aurelia-logging/dist/aurelia-logging.d.ts",
    "aurelia-logging-console": "npm:aurelia-logging-console/dist/aurelia-logging-console.d.ts",
    "aurelia-metadata": "npm:aurelia-metadata/dist/aurelia-metadata.d.ts",
    "aurelia-pal": "npm:aurelia-pal/dist/aurelia-pal.d.ts",
    "aurelia-pal-browser": "npm:aurelia-pal-browser/dist/aurelia-pal-browser.d.ts",
    "aurelia-path": "npm:aurelia-path/dist/aurelia-path.d.ts",
    "aurelia-polyfills": "npm:aurelia-polyfills/dist/aurelia-polyfills.d.ts",
    "aurelia-route-recognizer": "npm:aurelia-route-recognizer/dist/aurelia-route-recognizer.d.ts",
    "aurelia-router": "npm:aurelia-router/dist/aurelia-router.d.ts",
    "aurelia-task-queue": "npm:aurelia-task-queue/dist/aurelia-task-queue.d.ts",
    "aurelia-templating": "npm:aurelia-templating/dist/aurelia-templating.d.ts",
    "aurelia-templating-binding": "npm:aurelia-templating-binding/dist/aurelia-templating-binding.d.ts",
    "aurelia-templating-resources": "npm:aurelia-templating-resources/dist/aurelia-templating-resources.d.ts",
    "aurelia-templating-router": "npm:aurelia-templating-router/dist/aurelia-templating-router.d.ts",
    "aurelia-bootstrapper-webpack": "npm:aurelia-bootstrapper-webpack/dist/aurelia-bootstrapper-webpack.d.ts",
    "aurelia-dialog": "npm:aurelia-dialog/dist/aurelia-dialog.d.ts",
    "aurelia-validatejs": "npm:aurelia-validatejs/dist/aurelia-validatejs.d.ts",
    "aurelia-validation": "npm:aurelia-validation/aurelia-validation/aurelia-validation.d.ts",
    "aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge/dist/aurelia-kendoui-bridge.d.ts",
    "aurelia-materialize-bridge": "npm:aurelia-materialize-bridge/dist/aurelia-materialize-bridge.d.ts",
    "es6-collections": "registry:dt/es6-collections#0.5.1+20160316155526",
    "es6-promise": "github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#24e12a7af994afa2226af70fbfae0adc78736a9e",
    "jquery": "registry:dt/jquery#1.10.0+20160417213236",
    "kendo-ui": "registry:dt/kendo-ui#2016.1.314+20160322151008",
    "materialize-css": "npm:@ryancavanaugh/materialize-css/materialize-css.d.ts"
  }
}

```

**Comment by genericuser-me** [comment]
I discussed this issue in typings too:https://github.com/typings/typings/issues/552

Please check from my comments onwards

**Comment by y2k4life** [comment]
Not knowing what it is or why I find that if there is no commit hash then typings does not like it to be in the `globalDependencies`. But if you move them to `dependencies` it works. Here is what I have

```
{
  "name": "aurelia-skeleton-navigation-typescript-webpack",
  "version": false,
  "globalDependencies": {
    "aurelia-fetch-client": "github:aurelia/fetch-client/dist/aurelia-fetch-client.d.ts#a97fa7b9484cd78d986b11e537394400c99d02fe",
    "bluebird": "registry:dt/bluebird#2.0.0+20160319051630",
    "bootstrap": "registry:dt/bootstrap#3.3.5+20160316155526",
    "bootstrap.datepicker": "registry:dt/bootstrap.datepicker#0.0.0+20160505185215",
    "es6-collections": "registry:dt/es6-collections#0.5.1+20160316155526",
    "jquery": "registry:dt/jquery#1.10.0+20160417213236",
    "numeraljs": "registry:dt/numeraljs#0.0.0+20160316155526"
  },
  "dependencies": {
    "aurelia-binding": "github:aurelia/binding/dist/aurelia-binding.d.ts",
    "aurelia-bootstrapper": "github:aurelia/bootstrapper/dist/aurelia-bootstrapper.d.ts",
    "aurelia-bootstrapper-webpack": "github:aurelia/bootstrapper-webpack/dist/aurelia-bootstrapper-webpack.d.ts",
    "aurelia-dependency-injection": "github:aurelia/dependency-injection/dist/aurelia-dependency-injection.d.ts",
    "aurelia-dialog": "github:aurelia/dialog/dist/aurelia-dialog.d.ts",
    "aurelia-event-aggregator": "github:aurelia/event-aggregator/dist/aurelia-event-aggregator.d.ts",
    "aurelia-framework": "github:aurelia/framework/dist/aurelia-framework.d.ts",
    "aurelia-history": "github:aurelia/history/dist/aurelia-history.d.ts",
    "aurelia-history-browser": "github:aurelia/history-browser/dist/aurelia-history-browser.d.ts",
    "aurelia-loader": "github:aurelia/loader/dist/aurelia-loader.d.ts",
    "aurelia-loader-webpack": "github:aurelia/loader-webpack/dist/aurelia-loader-webpack.d.ts",
    "aurelia-logging": "github:aurelia/logging/dist/aurelia-logging.d.ts",
    "aurelia-logging-console": "github:aurelia/logging-console/dist/aurelia-logging-console.d.ts",
    "aurelia-metadata": "github:aurelia/metadata/dist/aurelia-metadata.d.ts",
    "aurelia-pal": "github:aurelia/pal/dist/aurelia-pal.d.ts",
    "aurelia-pal-browser": "github:aurelia/pal-browser/dist/aurelia-pal-browser.d.ts",
    "aurelia-path": "github:aurelia/path/dist/aurelia-path.d.ts",
    "aurelia-polyfills": "github:aurelia/polyfills/dist/aurelia-polyfills.d.ts",
    "aurelia-route-recognizer": "github:aurelia/route-recognizer/dist/aurelia-route-recognizer.d.ts",
    "aurelia-router": "github:aurelia/router/dist/aurelia-router.d.ts",
    "aurelia-task-queue": "github:aurelia/task-queue/dist/aurelia-task-queue.d.ts",
    "aurelia-templating": "github:aurelia/templating/dist/aurelia-templating.d.ts",
    "aurelia-templating-binding": "github:aurelia/templating-binding/dist/aurelia-templating-binding.d.ts",
    "aurelia-templating-resources": "github:aurelia/templating-resources/dist/aurelia-templating-resources.d.ts",
    "aurelia-templating-router": "github:aurelia/templating-router/dist/aurelia-templating-router.d.ts",
    "moment": "registry:npm/moment#2.10.5+20160211003958"
  }
}

```

Based on my rule above then why is `moment` which has a version tag not a global? I don't know. I try not to understand this, I just try to get it to work. Understanding will come later.

**Comment by genericuser-me** [comment]
ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(20,23): error TS2304: Cannot find name 'Request'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(20,35): error TS2304: Cannot find name 'Request'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(20,45): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(20,64): error TS2304: Cannot find name 'Request'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(20,74): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(30,34): error TS2304: Cannot find name 'Request'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(30,44): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(30,63): error TS2304: Cannot find name 'Request'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(30,73): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(39,25): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(39,45): error TS2304: Cannot find name 'Request'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(39,57): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(39,76): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(50,42): error TS2304: Cannot find name 'Request'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(50,54): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(50,73): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(71,13): error TS2304: Cannot find name 'Headers'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(76,17): error TS2304: Cannot find name 'BufferSource'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(76,43): error TS2304: Cannot find name 'URLSearchParams'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(261,16): error TS2304: Cannot find name 'Request'.

ERROR in C:\prj\Project\MyApplication\typings\modules\aurelia-fetch-client\index.d.ts
(261,63): error TS2304: Cannot find name 'Response'.

ERROR in C:\prj\Project\MyApplication\typings\globals\aurelia-validatejs\index.d.ts
(16,24): error TS2307: Cannot find module 'validate.js'.

**Comment by icanhasjonas** [comment]
@genericuser-me it seems your `typings.json` is a bit outdated? 
I followed the steps here (http://blog.durandal.io/2016/06/10/where-did-my-typescript-go/) and had a working typescript project running in no time.

**Comment by genericuser-me** [comment]
@icanhasjonas  I am confused what to change in my typings, can you please help?

tsconfig.json
```

{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  },
  "filesGlob": [
    "./src/**/*.ts",
    "./node_modules/aurelia-*/dist/aurelia-*.d.ts",
    "./typings/index.d.ts",
    "./third-party/typed-json/typed-json.d.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "atom": {
    "rewriteTsconfig": true
  }
}

```

typings.json:
```

{
  "name": "aurelia-skeleton-navigation-typescript-webpack",
  "version": false,
  "dependencies": {
    "moment": "npm:moment/moment.d.ts",
     "aurelia-binding": "npm:aurelia-binding/dist/aurelia-binding.d.ts",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts",
     "aurelia-event-aggregator": "npm:aurelia-event-aggregator/dist/aurelia-event-aggregator.d.ts",
    "aurelia-fetch-client": "npm:aurelia-fetch-client/dist/aurelia-fetch-client.d.ts",
    "aurelia-framework": "npm:aurelia-framework/dist/aurelia-framework.d.ts",
    "aurelia-history": "npm:aurelia-history/dist/aurelia-history.d.ts",
    "aurelia-history-browser": "npm:aurelia-history-browser/dist/aurelia-history-browser.d.ts",
    "aurelia-loader": "npm:aurelia-loader/dist/aurelia-loader.d.ts",
    "aurelia-loader-webpack": "npm:aurelia-loader-webpack/dist/aurelia-loader-webpack.d.ts",
    "aurelia-logging": "npm:aurelia-logging/dist/aurelia-logging.d.ts",
    "aurelia-logging-console": "npm:aurelia-logging-console/dist/aurelia-logging-console.d.ts",
    "aurelia-metadata": "npm:aurelia-metadata/dist/aurelia-metadata.d.ts",
    "aurelia-pal": "npm:aurelia-pal/dist/aurelia-pal.d.ts",
    "aurelia-pal-browser": "npm:aurelia-pal-browser/dist/aurelia-pal-browser.d.ts",
    "aurelia-path": "npm:aurelia-path/dist/aurelia-path.d.ts",
    "aurelia-polyfills": "npm:aurelia-polyfills/dist/aurelia-polyfills.d.ts",
    "aurelia-route-recognizer": "npm:aurelia-route-recognizer/dist/aurelia-route-recognizer.d.ts",
    "aurelia-router": "npm:aurelia-router/dist/aurelia-router.d.ts",
    "aurelia-task-queue": "npm:aurelia-task-queue/dist/aurelia-task-queue.d.ts",
    "aurelia-templating": "npm:aurelia-templating/dist/aurelia-templating.d.ts",
    "aurelia-templating-binding": "npm:aurelia-templating-binding/dist/aurelia-templating-binding.d.ts",
    "aurelia-templating-resources": "npm:aurelia-templating-resources/dist/aurelia-templating-resources.d.ts",
    "aurelia-templating-router": "npm:aurelia-templating-router/dist/aurelia-templating-router.d.ts"
  },
  "globalDependencies": {    
    "aurelia-bootstrapper-webpack": "npm:aurelia-bootstrapper-webpack/dist/aurelia-bootstrapper-webpack.d.ts",
    "aurelia-dialog": "npm:aurelia-dialog/dist/aurelia-dialog.d.ts",
    "aurelia-validatejs": "npm:aurelia-validatejs/dist/aurelia-validatejs.d.ts",
    "aurelia-validation": "npm:aurelia-validation/aurelia-validation/aurelia-validation.d.ts",
    "aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge/dist/aurelia-kendoui-bridge.d.ts",
    "aurelia-materialize-bridge": "npm:aurelia-materialize-bridge/dist/aurelia-materialize-bridge.d.ts",
    "es6-collections": "registry:dt/es6-collections#0.5.1+20160316155526",
    "es6-promise": "github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#24e12a7af994afa2226af70fbfae0adc78736a9e",
    "jquery": "registry:dt/jquery#1.10.0+20160417213236",
    "kendo-ui": "registry:dt/kendo-ui#2016.1.314+20160322151008",
    "materialize-css": "npm:@ryancavanaugh/materialize-css/materialize-css.d.ts"
  }
}

```

**Comment by genericuser-me** [comment]
@niieani  can you please help

**Comment by EisenbergEffect** [comment]
If you have all the latest aurelia libs installed via npm, you should not need typings for them anymore. They all specify the `typings` field which can be automatically picked up by the TS compiler when your tsconfig is set to use `"moduleResolution": "node"`. If you aren't using npm for your libraries you should be able to `typings install github:aurelia/library-name` for whatever libraries you need. All our libraries now specify a `typings.json` file as well to meet this need. I'll let @niieani add any further thoughts.

**Comment by genericuser-me** [comment]
@EisenbergEffect  
Did the following steps:

1. Deleted node modules
2. deleted typings folder
3. modified tsconfig
4. npm install
5. npm run dev

latest tsconfig:
```

{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
     "moduleResolution": "node",
    "sourceMap": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  },
  "filesGlob": [
    "./src/**/*.ts",
    "./node_modules/aurelia-*/dist/aurelia-*.d.ts",
    "./typings/index.d.ts",
    "./third-party/typed-json/typed-json.d.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "atom": {
    "rewriteTsconfig": true
  }
}

```

Did not run typings install.

Ran npm run dev, getting many errors like these
```

ERROR in ./src/app.ts
(4,29): error TS2307: Cannot find module 'aurelia-dialog'.
```

**Comment by atsu85** [comment]
@genericuser-me
>  I am confused what to change in my typings, can you please help?

See [Updating From 0.x to 1.0?](https://github.com/typings/typings#updating-from-0x-to-10).

 > C:\prj\Project\myapp>typings install
typings ERR! message Attempted to compile "aurelia-dependency-injection" as a global module, but it looks like an external module. Did you want to enable the global flag?

This means that you tried to install typings for library that was expected to be global module (as it is inside typings.json "globalDependencies" or the same might happen when You execute `typings install github:aurelia/dependency-injection --save --global`). The reason why it happens is explained in [Where did my TypeScript go!?](http://blog.durandal.io/2016/06/10/where-did-my-typescript-go/) blog post. Basically it means that "aurelia/dependency-injection" (like all other aurelia TS definitions) used to be in global module format, that is why they were installed with `--global` and stored in "globalDependencies", but now the format has changed, and now latest aurelia TS definitions should be installed without `--global` flag, so they would end up in "dependencies" section instead of "globalDependencies"

**Comment by atsu85** [comment]
Another thing to note, is that the dependencies in tsconfig.json are not locked to particular version(commit hash not included) and now You (probably) got beta2 versions where the change was done. If the record in typings.json had been in a format like this:
``"aurelia-dependency-injection": "github:aurelia/dependency-injection#someCommitHashToLockDownTo",`
instead of 
`"aurelia-dependency-injection": "github:aurelia/dependency-injection",`
then it would not had happened. 

However (to my current understanding) neither of them are perfect:
1) when you don't lock down the typings version, you get the latest version of TS declarations instead of version that is actually used by Your application - this may cause some issues due to versions mismatch
2) when you lock down the typings version to the version of the library Your application uses, You'll need to manually update typings versions after updating application library version - lots of manual work

If someone knows a better approach to resolve both issues listed above, I'd be glad to hear it.

**Comment by genericuser-me** [comment]
if I just do npm run dev, I get cannot find module

if I do typings install and then npm run dev I get "duplicate identifier"

**Comment by genericuser-me** [comment]
why does npm run dev, add the typings in global folder? I am totally lost.

This is my npm run command:

` webpack-dev-server --config webpack.config.js --hot --inline --progress --devtool eval`

here is my webpack.config.js

```
/*eslint-disable no-var*/

var path = require('path');
var AureliaWebpackPlugin = require('aurelia-webpack-plugin');
var ProvidePlugin = require('webpack/lib/ProvidePlugin');

module.exports = {
  root: [
        path.resolve('./'),
        path.resolve('aurelia-kendoui-bridge/vendors/js')
  ],
  resolve: {
    extensions: ['', '.js', '.ts'],
    modulesDirectories: ['node_modules', 'aurelia-kendoui-bridge/vendors/js'],
    alias: {
      'materialize': 'materialize-css/dist/css/materialize.css' 
    }

  },
  devServer: {
    host: 'localhost',
    port: 8000
  },
  entry: {
    main: [
      './src/main'
    ]
  },
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'bundle.js'
  },
  plugins: [
    new AureliaWebpackPlugin({
          includeSubModules: [
              { moduleId: 'aurelia-kendoui-bridge', include: /(template|autocomplete|multiselect|datepicker|valueconverters)/ },
              { moduleId: 'aurelia-materialize-bridge', include: /(navbar|card|select|dropdown|input|button|tooltip|waves|footer|switch)/ },
              { moduleId: 'aurelia-dialog' },
              { moduleId: 'aurelia-validatejs'}
          ]
      }),
    new ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery' // this doesn't expose jQuery property for window, but expose it to every module
    })
  ],
  module: {
      loaders: [
        { test: /\.ts$/, loader: 'ts-loader' },
        { test: /\.css?$/, loader: 'style!css', exclude: /(aurelia-dialog|aurelia-materialize-bridge)/ },
        { test: /\.css?$/, loader: 'raw', include: /(aurelia-dialog|aurelia-materialize-bridge)/ },
        { test: /\.html$/, loader: 'raw' },
        { test: /\.json$/, loader: 'raw' },
        { test: /\.(png|gif|jpg)$/, loader: 'url-loader?limit=8192' },
        { test: /\.woff2(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader?limit=10000&minetype=application/font-woff2' },
        { test: /\.woff2(\?v=[0-9]\.[0-9]\.[0-9][0-9])?$/, loader: 'url-loader?limit=10000&minetype=application/font-woff2' },
        { test: /\.woff(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader?limit=10000&minetype=application/font-woff' },
        { test: /\.woff(\?v=[0-9]\.[0-9]\.[0-9][0-9])?$/, loader: 'url-loader?limit=10000&minetype=application/font-woff' },
        { test: /\.woff(\?[a-z0-9]+)?$/, loader: 'url-loader?limit=10000&minetype=application/font-woff' },
        { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9])?$/, loader: 'file-loader' },
        { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'file-loader' },
        { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9][0-9])?$/, loader: 'file-loader' },
        { test: /\.(ttf|eot|svg)(\?[a-z0-9]+)?$/, loader: 'file-loader' }
      ]
  }
};

```

**Comment by EisenbergEffect** [comment]
@genericuser-me If your project has a typings.json file, take a look in there. They are probably listed in the global section, rather than in the dependencies section.

**Comment by genericuser-me** [comment]
I moved it to dependencies, still get the same issue mentioned above

**Comment by niieani** [comment]
It really depends which version of typings you are using.
If you are using the ones from the current skeleton, they should be used in
the globalDependencies. If you've manually installed the latest d.ts from
GitHub, they not should be moved to dependencies section.

**Comment by genericuser-me** [comment]
I installed them,

npm install typings --global

npm install

typings install

**Comment by genericuser-me** [comment]
typings version is 1.2.0

**Comment by genericuser-me** [comment]
Its going in circles, if I put typings in dependencies, it gives:

C:\prj\Project\myapp>typings install
typings ERR! message Attempted to compile "aurelia-dependency-injection" as a global module, but it looks like an external module. Did you want to enable the global flag?


If I move if from global, it gives duplicate. What am I doing wrong??

**Comment by unional** [comment]
Three thoughts:
- Check `AureliaWebpackPlugin` to see if they are doing something there..
- As @EisenbergEffect said, you don't need to use `typings` for `aurelia` anymore (as you are using node + webpack). Remove those dependencies.
- Try to set `tsconfig.json/module = "commonjs"`

**Comment by unional** [comment]
- Create a dummy repo to reproduce this on github, so we can take a look into it.

**Comment by genericuser-me** [comment]
@unional here is the code: https://gist.run/?id=f2101a2deecf26a69bbca8be8abf24c9

steps that I follow:

1. npm install
2. typings install 

I get the following error here:

```
C:\prj\Project\myapp>typings install
typings ERR! message Attempted to compile "aurelia-dependency-injection" as a global module, but it looks like an external module. Did you want to enable the global flag?

typings ERR! cwd C:\prj\Project\myapp
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v6.2.0
typings ERR! typings -v 1.2.0

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```

**Comment by unional** [comment]
@genericuser-me , please clean it up first. Said many times, the `aurelia-*` should not be there.

**Comment by genericuser-me** [comment]
@unional Apologies, I have been going in circles trying to make it work. I removed it from typings.json. Now I get errors for aurelia-fetch-client and validate.js

```
ERROR in C:\prj\Project\MyApp\node_modules\aurelia-fetch-client\dist\aurelia-fetch-client.d.ts
(17,23): error TS2304: Cannot find name 'Request'.
```


```
ERROR in C:\prj\Project\MyApp\typings\globals\aurelia-validatejs\index.d.ts
(16,24): error TS2307: Cannot find module 'validate.js'.
```

**Comment by unional** [comment]
Now it looks better.

Check the remaining `aurelia-*` Some of them are from `aurelia` and has typings in them, so you don't need those either.

Also, it's `typings.json`, not `typings.js`

first error about `Request` is something to do with `lib.d.ts`, which I'm not familiar with. Need other people to look and see why it is not loaded or is there a better alternatives. @EisenbergEffect This one could break other people too.

The second on I think you can solve it by removing it. It by `aurelia` and is included.

**Comment by genericuser-me** [comment]
Filename is just typo. I have correct in my code :)

I did not understand this line - "The second on I think you can solve it by removing it. It by aurelia and is included."

**Comment by genericuser-me** [comment]
@EisenbergEffect  can you please help why "aurelia-fetch-client" is not getting loaded

**Comment by unional** [comment]
> Check the remaining aurelia-* Some of them are from aurelia and has typings in them, so you don't need those either.

That's what I mean

**Comment by MrHayato** [comment]
for the `Cannot find name Request`, you need to add the typings for fetch. You can do that by adding `"fetch": "npm:aurelia-fetch-client/doc/whatwg-fetch.d.ts",` to your "globalDependencies" in typings.json

**Comment by genericuser-me** [comment]
@unional Ok. thanks

@MrHayato Thanks, that took out fetch errors, now only 2 more:

```
ERROR in C:\prj\Project\MyApp\typings\globals\aurelia-validatejs\index.d.ts
(16,24): error TS2307: Cannot find module 'validate.js'.
```

```
ERROR in ./src/main.ts
(3,25): error TS2307: Cannot find module 'aurelia-bootstrapper-webpack'.
```

**Comment by genericuser-me** [comment]
Got the latest version for aurelia-validations, Removed it from typings.json and now the error changed to:

```
ERROR in C:\prj\ContractsV2\MDCOContractsWeb\node_modules\aurelia-validatejs\dist\aurelia-validatejs.d.ts
(8,22): error TS2307: Cannot find module 'validate.js'.
```

**Comment by unional** [comment]
@EisenbergEffect , I can't find typings for `validate.js`.

Need to:
- create the typings and add to `typings/registry`
- `typings install -S validate.js` in `aurelia-validatejs`

**Comment by unional** [comment]
Actually it seems like it is not used in export. Perhaps you need to adjust your generating script to remove that.

**Comment by genericuser-me** [comment]
@unional  I am totally lost, from where do I remove it

**Comment by unional** [comment]
> that comment was for @EisenbergEffect.

Yes

In this case we don't need because `aurelia-validatejs` doesn't really use it in the typings. However, contribution is always welcome.

**Comment by genericuser-me** [comment]
@unional  @EisenbergEffect created a typings file for validate.js. Please take a look if it is ok.

I tried to add this to node modules and added the reference to aurelia-validatejs.d.ts, it compiled oj but gave runtime error that cannot find module "./aurelia-validate.js". Can you please help?

**Comment by genericuser-me** [comment]
This error comes from main.ts. It looks for plugin
```
bootstrap((aurelia: Aurelia): void => {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
 .plugin('aurelia-validatejs')
        .plugin("aurelia-materialize-bridge")
        .plugin('aurelia-dialog') });
```

and so on.. if I comment all these, it fails for aurelia-templating-resource

![image](https://cloud.githubusercontent.com/assets/17732922/16166974/0f8677b8-34be-11e6-9e26-e3880efc7582.png)

**Comment by genericuser-me** [comment]
@EisenbergEffect can you please help?

**Comment by EisenbergEffect** [comment]
@niieani Are all the webpack skeletons broken now, including the currently released skeleton? or can developers successfully use our released skeleton still and avoid this trouble?

**Comment by y2k4life** [comment]
@EisenbergEffect I think what is happening are two things. One is the versioning in the `packages.json` for `webpack-plugin` module is not working and instead of a minor update to 1.0.4 a major update to 2.x.x is done. Second is issues with the whole typings, as you mentioned in a blog http://blog.durandal.io/2016/06/10/where-did-my-typescript-go/. The skeleton typing.json needs to be updated in line with that blog post. BTW that blog post is confusing as to where to go and what to do. Therefore there are two issues. When you download the skeleton, in my case `skeleton-navigation-1.0.0-beta.1.2.6` and you do the `npm install` the most recent version of `webpack-plugin` is  installed instead of `1.0.0-beta.1.0.4`. Because of various issues with the 2.x.x that don't work that causes issues. Then you have all the issues with the typings mentioned above. I was able to get it to work by removing `^` for the version number and then update typings.json from the most recent commit to the skeleton on github. I inferred what the blog was stating. I think the challenge now is that the skeleton for webpack was rewritten to included both TS and ES6 and it is a challenge to make a minor release to fix these issues without the major design change.

**Comment by niieani** [comment]
@EisenbergEffect Both Webpack skeleton's should be working fine under MacOS
and Linux. Windows still has issues. People have issues mostly because they
are in partially migrated state, where some files or packages are from the
old, and some are new skeleton.

**Comment by genericuser-me** [comment]
@niieani can you please help with what files should I take? I have posted my code here : https://gist.run/?id=f2101a2deecf26a69bbca8be8abf24c9

Can you please guide where I am going wrong? I am using windows.

**Comment by Vheissu** [comment]
Based on my use of the latest version of the plugin and even the couple of releases that came before it, these issues no longer exist on either macOS or Windows. I think this issue can now be safely closed.
