### ISSUE TITLE
Infinite loop is back (on windows, css only)

### ISSUE THREAD

**Issue by JoschaMetze** [aurelia/webpack-plugin#38]
Hi,

I experienced the infinite loop issue again (even on beta 2.0.3). But this time it's linked to css and html . I'm trying to integrate the aurelia-materialize-bridge with the new webpack-plugin beta 2.
What works for aurelia-dialog (modifying package.json within the plugin to reference the needed resources) fails within aurelia-materialize-bridge:

<aurelia-materialize-bridge> [breadcrumbs.html] required "././aurelia-materialize-bridge/dist/commonjs/breadcrumbs/breadcrumbs.html" from "node_modules/aurelia-materialize-bridge/dist/commonjs/breadcrumbs/breadcrumbs.html".
<aurelia-materialize-bridge> [breadcrumbs.html] required "./aurelia-materialize-bridge/dist/commonjs/breadcrumbs/breadcrumbs.css" from "!!css!node_modules/aurelia-materialize-bridge/dist/commonjs/breadcrumbs/breadcrumbs.css".

This happens when trying to include the .js, the .css or the .html-file (in build->resources)
Running on windows.

Thanks,
Joscha

**Comment by Vheissu** [comment]
All infinite loop and path issues on Windows should now be fixed. I was in the same boat and todays release seems to address all webpack pathing issues (including resolution) on both Windows and macOS environments.
