### ISSUE TITLE
Restrict source files and split bundles

### ISSUE THREAD

**Issue by crbranch** [aurelia/webpack-plugin#4]
Would it be possible to add a few more examples to the ReadMe?  There are a few things I'm not clear about:

1. It seems like the plugin tries to bundle *everything* under `./src`.  Is there a way to restrict to certain files/patterns?  For example, I'd like an "opt-in" option to include only `*.ts`, `*.js`, `*.html`, etc. and exclude everything else (`*.bak`, `*.tmp`, `*.old`, etc.)  The ReadMe talks about `contextMap`, but my understanding is `contextMap` is for npm dependencies only and not applicable for `./src`, correct?

2. Is it possible to create multiple bundles for different "pages"?  The normal way to do this with webpack is to include multiple items in the `entry` element in webpack.config and let webpack follow the dependency chain for each, then use webpack's CommonsChunkPlugin, etc. to generate a bundle that extracts the shared/common code.  However, I'm not clear how this would work with the aurelia webpack plugin since the plugin seems to include all files?  If this is possible, an example webpack.config would be great.

And finally, thank you to @martijnboland and others who have contributed to this tool!

**Comment by martijnboland** [comment]
1. Currently there is no filtering option. Possibly, a regex filter option just like webpack's ContentReplacementPlugin (where this plugin is based on) could be added.

2. No, unfortunately that's not possible at this moment. The plugin just bundles all files because it cannot determine all dependencies at build time due to Aurelia's dynamic loading.

**Comment by fabioluz** [comment]
+ 1 for multiple bundles

**Comment by Jenselme** [comment]
I am also very interested in multiple bundles. Any progress on that? Do you have any idea on how to implement that? I would like to try to do it.

**Comment by Vheissu** [comment]
@martijnboland Would Webpack 2.0 solve the aforementioned issues with multiple bundles support because dynamic loading of dependencies will be supported? If so, what is the compatibility like with Webpack 2.0 and the current loader plugin?

**Comment by martijnboland** [comment]
@Vheissu to be honest, I haven't seen anything in webpack 2 that will solve our current problems. To my knowledge, true dynamic loading like SystemJS or RequireJS do, is still not supported.

**Comment by ranjith86** [comment]
@martijnboland is there a way to configure contextmap to look into bower.json along with packages.json. Right now contextmap is build against node_modules, is there a way to configure it to support bower_components too.

**Comment by martijnboland** [comment]
@ranjith86 you can manually add a contextmap to the plugin config (webpack.config.js). 

Something like (not tested):
  
```
var bower = require('bower.json');
var fs = require('fs');

...

function getContextMap() {
  var contextMap = {};
  var bowerPackages = Object.keys(bower.dependencies || {});
  bowerPackages.forEach(function(moduleId) {
    var vendorPath = path.resolve('./bower_components', moduleId);
    var vendorPkgPath = path.resolve(vendorPath, 'bower.json');
    var vendorPkg = JSON.parse(fs.readFileSync(vendorPkgPath, 'utf8'));
    if (vendorPkg.main) {
      contextMap[moduleId] = path.resolve(vendorPath, vendorPkg.main);
    }
  });
  return contextMap;
}

...

plugins: [
    new AureliaWebpackPlugin({
      contextMap: getContextMap()
    }),

   ...

```

**Comment by ranjith86** [comment]
@martijnboland i will give that a try and keep you posted

**Comment by ranjith86** [comment]
@martijnboland thanks for your suggestion. I modified the logic a little bit to depend on bower.json first and then package.json. Aurelia bower packages doesn't have "main" attribute populated in bower.json, so i had to use package.json. Below is the snippet...

```
var fileSystem = require('fs');

function getContextMap() {
  var contextMap = {};
  var bower = JSON.parse(fileSystem.readFileSync(path.resolve('./bower.json')));
  var bowerPackages = Object.keys(bower.dependencies || {});
  bowerPackages.forEach(function(moduleId) {
    var vendorPath = path.resolve('./bower_components', moduleId);
    var vendorPkgPath = path.resolve(vendorPath, 'bower.json');
    if(vendorPkgPath) {
      var vendorPkg = JSON.parse(fileSystem.readFileSync(vendorPkgPath, 'utf8'));
      if (vendorPkg.main) {
        if(!Array.isArray(vendorPkg.main) && (/\.js$/.test(vendorPkg.main))) {
          contextMap[moduleId] = path.resolve(vendorPath, vendorPkg.main);
        }
      }
      else {
        vendorPkgPath = path.resolve(vendorPath, 'package.json');
        if(vendorPkgPath) {
          vendorPkg = JSON.parse(fileSystem.readFileSync(vendorPkgPath, 'utf8'));
          if (vendorPkg.browser || vendorPkg.main) {
            contextMap[moduleId] = path.resolve(vendorPath, vendorPkg.browser || vendorPkg.main);
          }
        }
      }
    }
  });
  return contextMap;
}

```

**Comment by EisenbergEffect** [comment]
If we need to make improvements in our bower packages, just let us know what to do. Submit a PR as an example and we can get things updated.

**Comment by ranjith86** [comment]
@EisenbergEffect sure I will submit a PR for this request. It'a minor one. If there is a "main" attrubute in bower.json file similar to "main" attribute in package.json for aurelia packages, custom context map(aurelia-webpack) can rely on "main" for bower aurelia packages rather than relying on package.json/main.

**Comment by ranjith86** [comment]
@EisenbergEffect submitted PR for aurelia-router package with bower.json one line change. If you review and accept those changes, I can submit PRs for this minor change for all other packages too. Also, I got aurelia skeleton working with wekpack and bower. Do you think it is useful to include in skeleton package?

**Comment by EisenbergEffect** [comment]
Let me review that. It might be easier for us to replicate the change ourselves rather than processing a bunch of PRs. I'll let you know.

**Comment by EisenbergEffect** [comment]
Fixes coming into plugins and skeletons now...

**Comment by EisenbergEffect** [comment]
Fixed in https://github.com/aurelia/skeleton-navigation/commit/1df111d47cd5303af7442b3152dc4201be4ffbf9
