### ISSUE TITLE
"Template markup must be wrapped in a <template>" error with Polymer.

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/webpack-plugin#40]
I'm converting an Aurelia-Polymer Project to work with Webpack.

Here is a working example: [skeleton-navigation/skeleton-webpack](https://github.com/HIRANO-Satoshi/skeleton-navigation/tree/master/skeleton-webpack)

It works with this code.
```
<template>
<link rel="import" href="/bower_components/paper-button/paper-button.html">
```

But not with this code;

```
<link rel="import" href="/bower_components/paper-button/paper-button.html">
<template>
```
with this error.

```
Unhandled rejection Error: Template markup must be wrapped in a <template> element e.g. <template> <!-- markup here --> </template>
```

May be this not an issue. But both cases worked with JSPM.

**Comment by EisenbergEffect** [comment]
I'm not sure how it worked with jspm. There's a strict guard in the codebase to ensure that html is wrapped with a template.
