### ISSUE TITLE
Dependency not found during production build

### ISSUE THREAD

**Issue by JoschaMetze** [aurelia/webpack-plugin#45]
First of all, thanks for fixing the nasty windows bugs, it works like a charm for me now. But only in development mode (e.g. build:dev). As soon as I set the process.env.ENV and process.env.NODE_ENV to production it fails again looking for aurelia-materialize-bridge. 
Way to reproduce (using the new skeleton (with typescript)):
-Add aurelia-materialize-bridge (and add their needed ressources in package.json) via npm and include it (e.g. in index.js)
-modify webpack.base-dev.js to define production instead of develop in ENV-line.
-start build (e.g. npm run build:dev)

Thanks again for your work
Joscha

**Comment by niieani** [comment]
There's no `webpack.base-dev.js` in the latest skeleton. Please try to use the config file from the new skeleton. Also, please paste the actual error the next time. I'll close this for now and reopen if you can confirm this is a bug in the up-to-date config file.

**Comment by JoschaMetze** [comment]
Just to add the resolution for future reference. The difference was in the 'npm ls' call. It returns different lists (dependencies vs devDependencies). Should have thought about that before, silly me.
