### ISSUE TITLE
progressbar (XHR downloading bundles)

### ISSUE THREAD

**Issue by flieks** [aurelia/webpack-plugin#50]
Hi,

I implemented XHR download of the main-1.0.0-beta.js entry bundle file to show progress to user.

Unfortunately this bundle then downloads a much bigger bundle file (0-1.0.0-beta.js).

Can i change the webpack.prod.config so it only produces 1 bundle file? 
This is my [config file](https://gist.github.com/flieks/771b0e686a3a931f6931e1e069760bd6).

Greetings
Felix

**Comment by niieani** [comment]
Sure, I'd you like everything to be contained in one bundle, use the LimitChunkCountPlugin: https://github.com/webpack/docs/wiki/list-of-plugins#limitchunkcountplugin.
Note, that this is not an aurelia-related question.

**Comment by flieks** [comment]
Thanks you very much, that worked to make 1 package :)
