### ISSUE TITLE
Custom plugin in a folder parallel to src ?

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/webpack-plugin#52]
Using webpack 1.0 I could add a custom plugin in a folder `myplugin`, parallel to `/src`, to webpack.config:

```javascript
   new AureliaWebpackPlugin({
      includeSubModules: [
        {moduleId: 'myplugin'}
      ],
      contextMap: {
        'myplugin': 'myplugin/index.js'
      }
```

and request in `main.js`:

```javascript
    .feature('myplugin')
```

How to achieve the same using webpack 2.0 ?

I tried declaring the srcDir as array and adding the path to `myplugin` there, did not work:

```javascript
const rootDir =  path.resolve();
const srcDir = [path.resolve('src'), path.resolve(`myplugin`)];
const outDir = path.resolve('dist');
```
Also tried extending the dev configuration like this: 

```javascript
      require('@easy-webpack/config-generate-index-html')
        ({minify: false}),

        {
          plugins: [
            new AureliaWebpackPlugin({
              includeSubModules: [
                {moduleId: 'myplugin'}
              ],
              contextMap: {
                'myplugin': 'myplugin/index.js'
              }
            })
          ]
        }
    );
    break;
```
and getting error:
```shell
Uncaught (in promise) Error: Cannot find module './myplugin/index'.(…)
```

**Comment by EisenbergEffect** [comment]
@niieani Ping.

**Comment by niieani** [comment]
Both `includeSubModules` and `contextMap` were deprecated in the latest versions of the Webpack Plugin.
You'll need to declare your plugin as a resource as described both in the current readme files of both the skeleton and the webpack-plugin: [here](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack#resource-and-bundling-configuration) and [here](https://github.com/aurelia/webpack-plugin#module-resource-resolution).

**Comment by niieani** [comment]
It seems like a nice feature request to be able to provide an array as the `srcDir`. I'll add an issue to track its implementation.

**Comment by niieani** [comment]
One more thing @bsrdjan the build resources are defined relative to the `srcDir`, therefore if your plugin is in a parent directory, you should defined its path as: `../myplugin/index`

**Comment by bsrdjan** [comment]
Thanks for the quick response and helpful hint, this config works:

**package.json**

```javascript
  "build": {
      "resources": [
       {
          "path": "../myplugin/index"
        }
      ]
    }
```

**main.js**

```javascript
    .feature('../myplugin')
```

**index.js**

```javascript
  aurelia.setRoot('app', rootElement);
```

The `main.js` is in my case in root folder and the `../myplugin` in `main.js` looks wrong, unless you know it is relative to `src`, not the root folder, of the `main.js` itself.

Would it be possible to set the `src` to the root folder, and include only resources in `/src` and `/myplugin' folders ?

**Comment by niieani** [comment]
@bsrdjan Adding a Regex exclude-filter to the `src` is a planned feature. However it would seem easier just to put your `main.js` into the `src` folder. At this time, every file in the `src` folder is treated as a build resource (without the need of it being manually declared), that's why changing your src folder to the parent isn't really advisable, especially since there is no Regex filtering option available, and since you would have to maintain the exclude list.

We might consider adding a white-list filter at some point though. That might be a bit easier than filtering/excluding not needed resources.
