### ISSUE TITLE
Resource resolution not working

### ISSUE THREAD

**Issue by aaronroberson** [aurelia/webpack-plugin#57]
*I'm submitting a bug report*

*Library Version:*
@easy-webpack/config-aurelia 2.0.1

*Operating System:*
OSX 10.x

*Node Version:*
4.3.2

*NPM Version:*
3.9.2

*Webpack AND Version*
webpack 2.1.0-beta.17

*Browser:*
Chrome

*Language:*
ESNext

*Current behavior:*

I’m getting errors when trying to use module resolution for relative paths.

```
Unable to resolve common/
Unable to resolve components/
Unable to resolve views/
Unable to resolve views/collections
Unable to resolve views/info
Unable to resolve views/publish
Unable to resolve views/schema
Unable to resolve views/info
Unable to resolve views/thread-edit
Unable to resolve views/thread-target
Unable to resolve views/thread-translate
```

I have the following in package.json:
```
"aurelia": {
    "build": {
      "resources": [
        "common",
        "components",
        "views"
       ]
     }
  }
```

I have the following import statement in my JS files (located in various directories under `src`):

`import {AppService} from 'common/services/app.service';`

Where the `common` directory resides in the `src` directory at the top level. Same for `components` and `views`.

*Expected/desired behavior:*

I expect the `import` would resolve the path to `src/common` `src/views` and `src/components` respectively.

**Comment by niieani** [comment]
You can't currently declare directories in build resources, you need to specify every file. Please track: https://github.com/aurelia/webpack-plugin/issues/54
