### ISSUE TITLE
Aurelia require only accept js, html and css

### ISSUE THREAD

**Issue by atul221282** [aurelia/webpack-plugin#58]
![capture](https://cloud.githubusercontent.com/assets/4570393/17010057/ab0e4a58-4f3f-11e6-9573-d349b870990a.PNG)

**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32
* **Browser:**
all

* **Language:**
TypeScript 1.3

**Current behavior:**
<require from="nav-bar"></require> looks for nav-bar.js
<require from="nav-bar.html"></require> looks for nav-bar.html

**Expected/desired behavior:**
<require from="nav-bar.cshtml"></require> looks for nav-bar.cshtml.js thought it should look for nav-bar.cshtml

* **What is the expected behavior?**
Look for provided extension not the defualt if not found which is .js

* **What is the motivation / use case for changing the behavior?**
Use server side view i have jus addedd the image of what happen when u try to make call to server to get view with partialview(this returns html from partial view) and just view, which is cshtml
![capture2](https://cloud.githubusercontent.com/assets/4570393/17010121/328f45fe-4f40-11e6-8436-916dad2e09d7.PNG)

Top image is when I am trying to make call to server to give me the view second image is also trying to make call to server but aurelia appends .js in the end( **`<require from="nav-bar"></require>`**)

**Comment by niieani** [comment]
This should be working properly. When you provide a resource that exists. Alternative extensions (such as .js, .ts and .html) are only tested when exact match does not exist. Please provide more info of your use case and we can debug.

**Comment by atul221282** [comment]
This is my main app which uses nav-bar custom element to render my menu. I am trying to use mvc partial view for my nav-bar so that i can hide some section of nav-bar if user is logged in or not.
```
<template>
    <require from="nav-bar.cshtml"></require>
    <require from="bootstrap/css/bootstrap.css"></require>
    <nav-bar router.bind="router"></nav-bar>
    <div class="page-host">
        <router-view></router-view>
    </div>
</template>
```

Now when I run my app and look at my network call the aurelia is trying to get  **mybaseurl/dist/nav-bar.cshtml.js** which is wrong it should just straight away look for nav-bar.cshtml without any js.

Now one more requirement what if i decide to get view from other server and that case I would like to use my custom element as below

 <require from="http://localhost/AureliaTSApp/Template/Render?name=nav-bar"></require>

this is also not working, in my netowork tab of browser, it is looking for **http://localhost/AureliaTSApp/Template/Render?name=nav-bar.js**

The issue is if we don't provide extension or provide an extension that is other than css,html and js it will append .js in the end for each request

**Comment by niieani** [comment]
You seem to be using JSPM, not Webpack. This issue is on the wrong repo, try skeleton navigation. Closing.
