### ISSUE TITLE
TypeError: Cannot read property 'aurelia' of null

### ISSUE THREAD

**Issue by Vheissu** [aurelia/webpack-plugin#59]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.4.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.18

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript 2.0.0

**Current behavior:**
- Install a plugin which specifies its own resources using aurelia > build > resources such as `aurelia-dialog`
- In `main.ts` attempt to load the plugin `aurelia.use.plugin('aurelia-dialog')`
- Run `npm run watch`

**The above results in the following output:**

```
TypeError: Cannot read property 'aurelia' of null
    at getPackageMainDir (C:\Sites\reporting-application\node_modules\aurelia-webpack-plugin\dist\build-resources.js:293:32)
    at getRealModulePath (C:\Sites\reporting-application\node_modules\aurelia-webpack-plugin\dist\build-resources.js:326:39)
    at getRealPathUniversal (C:\Sites\reporting-application\node_modules\aurelia-webpack-plugin\dist\build-resources.js:303:55)
    at processFromPath (C:\Sites\reporting-application\node_modules\aurelia-webpack-plugin\dist\build-resources.js:357:18)
    at getResourcesOfPackage (C:\Sites\reporting-application\node_modules\aurelia-webpack-plugin\dist\build-resources.js:489:11)
    at Object._callee$ (C:\Sites\reporting-application\node_modules\aurelia-webpack-plugin\dist\build-resources.js:74:13)
    at tryCatch (C:\Sites\reporting-application\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Sites\reporting-application\node_modules\regenerator-runtime\runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Sites\reporting-application\node_modules\regenerator-runtime\runtime.js:95:21)
    at step (C:\Sites\reporting-application\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Sites\reporting-application\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
    at run (C:\Sites\reporting-application\node_modules\core-js\library\modules\es6.promise.js:87:22)
    at C:\Sites\reporting-application\node_modules\core-js\library\modules\es6.promise.js:100:28
    at flush (C:\Sites\reporting-application\node_modules\core-js\library\modules\_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This also seems to be any plugin which defines its own `aurelia: {build: resources: []}` configuration. The Webpack Plugin doesn't seem to be handling this at all. Even manually specifying the paths in my application `package.json` and removing the plugin resources definition results in the same error breaking the app.

**Expected/desired behavior:**
Plugins which define resources get appropriately parsed without error.

**Comment by EisenbergEffect** [comment]
@niieani Ping.

**Comment by niieani** [comment]
Seems like the plugin can't load the `package.json` file for your plugin for some reason. I've committed a fix https://github.com/aurelia/webpack-plugin/commit/b5b9fae58e696b340af1b64df23fa70a08c55b53, but that probably won't solve your issue. But try it. Not sure what could be the reason for it erroring like that for you though. It doesn't happen for me.

**Comment by Vheissu** [comment]
Just a note for anyone else coming across this. My issue was specifically related to using a scoped Npm package, eg. @scope/package-name and it appears as though the path was being split and then shifted, which meant the scope was being used as the module name and the rest ignored. This resulted in trying to resolve a module that technically didn't exist (node_modules/@scope/ opposed to node_modules/@scope/package-name).

**Comment by MikeBull94** [comment]
Did you find a workaround for this @Vheissu, other than just giving up on scoped packages?

**Comment by niieani** [comment]
@MikeBull94 I believe this was fixed. In any case, a brand new set of webpack plugins for aurelia is coming soon and it should be free of this sort of problems.

**Comment by MikeBull94** [comment]
Ah, I see. I was intentionally holding back my version of this plugin to a beta 1.0 version specifically due to issue #65. Hopefully everything will fix itself with the new versions of the webpack related plugins.

**Comment by niieani** [comment]
@MikeBull94 yes indeed, #65 is among the issues fixed by https://github.com/aurelia/skeleton-navigation/pull/714

**Comment by MikeBull94** [comment]
That commit seems to suggest ditching the webpack-plugin entirely. Will there be documentation for migrating existing projects that are currently reliant on the webpack-bootstrapper & webpack-plugin?

**Comment by niieani** [comment]
@MikeBull94 I'm sure we'll come up with something. 

It will be as simple as replacing the aurelia-webpack-plugin with [this set of plugins and loaders](https://github.com/aurelia/skeleton-navigation/blob/a5f8daab82738aad3b5eb40aeadd0cdd6af60e65/skeleton-typescript-webpack-experimental/webpack.config.ts#L302-L398).

If you use easy-webpack you'll only need to update the `easy-webpack/config-aurelia` package, the bootstrapper and loader-webpack to the next major versions.

**Comment by MikeBull94** [comment]
Thanks again @niieani. I don't use easy-webpack but will try update my configuration to depend on those plugins & loaders you just linked :pray:.

**Comment by niieani** [comment]
@MikeBull94 also note that the new versions of **aurelia-loader-webpack** and **aurelia-bootstrapper** still aren't released, so things might not work properly without those dependencies.

![justin-space-meditation-zen-l0COJ5gIPUN2vOj5u](https://camo.githubusercontent.com/7d3794e8a874c2fb5eec7551ee8a5bc88fc28447/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6c30434f4a35674950554e32764f6a35752f67697068792e676966>)

**Comment by MikeBull94** [comment]
Your configuration in that project also seems to be heavily reliant on webpack2, which as it is still in beta is not a solution I can run with.

Is there really no plan to fix issue #65? The only solution proposed is to abandon this plugin and the webpack-bootstrapper and use your new configuration (which includes way too much boilerplate, so I'd have to attempt to convert my configuration to exclude the bootstrapper & plugin in favour of your dependency suite, whilst *also* migrating from webpack 1 to webpack 2).

Is there a way to make this process less painful? All I want is the simple bugfix that was introduced in 1.0.0 of this plugin without it breaking hotreload (i.e. issue #65) - having to switch my build system to a beta version and having to rip out my configuration seems rather convoluted.

**Comment by niieani** [comment]
If it's not too complex, I'll see if it would be possible to fix it. But no promises. One of the main reasons for rewriting the aurelia-integration plugins from scratch was to ditch the messy context loading done by this plugin, and get a proper dependency graph setup. There were so many problems with the original approach that it just seemed reasonable to abandon it, rethink it all and start from scratch with a better idea. 

Going forward, I wouldn't recommend using webpack-plugin, as you may encounter other issues along the way (just see the huge list of issues both here and in the loader-webpack repos!).

On the other hand, I haven't tested the webpack-dependency-suite under Webpack 1, but it *might* just work. No idea.

**Comment by MikeBull94** [comment]
My main gripe with adopting webpack 2 with that configuration is the amount of bloat. That line range of code you linked me to would almost double the size of my current webpack configuration, and I'm sceptical of the usage of `RewriteModuleSubdirectoryPlugin`, `MappedModuleIdsPlugin`, `addLoadersCallback`, etc.

Seems to be a lot of unnecessary configuration vs the current solution of just `new AureliaWebPackPlugin()`.

This is comparing to my starter kit (https://github.com/MikeBull94/aurelia-typescript-webpack-starter/blob/master/webpack.config.js) which has a 70 line configuration which isn't hard for newcomers to comprehend. I don't see how anyone would start dissecting the configuration of that skeleton project, if they disagree/don't need half of the things that it's bringing in.

**Comment by niieani** [comment]
True, but you can abstract all that Aurelia-specific configuration out into a separate file if you don't want to "pollute" your config file.

The problem with this module, Aurelia Webpack Plugin, was that it did most of what the new set of plugins do (albeit in a different, worse way), but it did it as a closed black box, "magically". 

Now that it's all separate plugins and loaders, decoupled from Aurelia altogether, it's clear, configurable, plus you can remove what you don't want, or add more. It's much more transparent as to what's going on under the hood. 

Yeah, looks more "messy". But in the end I think the benefits outweigh the negatives of this change. It's also simpler to maintain and fix problems to smaller and simpler plugins and to test them.

And if you don't want a messy look, simple configuration files, that's why I created easy-webpack for. There are alternatives too, like [terse-webpack](https://github.com/ericclemmons/terse-webpack) which you might find more to your liking.
