### ISSUE TITLE
Webpack skeleton can run into Webpack bug in production because of separate bundles

### ISSUE THREAD

**Issue by niieani** [aurelia/webpack-plugin#61]
@sickboy commented on [Sun Jul 17 2016](https://github.com/aurelia/skeleton-navigation/issues/613)

[Uncaught TypeError: Cannot read property 'call' of undefined](https://github.com/webpack/webpack/issues/959#issuecomment-233172657)

The workaround:
- index.js: add to end: require('./src/main')
- webpack.config.js: 
  - Disable commonchunksplugin
 - change chunks section to: `{ 'app': ['./index'] }`

---

@niieani commented on [Sun Jul 17 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-233175260)

As linked, this seems to be a Webpack bug, I'm not so sure it belongs here, especially since it doesn't occur with the default configuration. 
This happens in production bundling only?

---

@sickboy commented on [Sun Jul 17 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-233175327)

@niieani it does happen with the default configuration, in production only at this time yes.
I also had interesting results with loading the bundles from local node server, vs CDN. The same bundle would work when loading from the local node server (single request limit?) but fail when loaded from CDN.

---

@niieani commented on [Sun Jul 17 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-233176027)

Does it happen every time?

---

@sickboy commented on [Sun Jul 17 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-233176134)

@niieani no it's a horrible bug, I wasted about 6 hours on this in the last 2 days, see my details in https://github.com/webpack/webpack/issues/959#issuecomment-233172657

Example:
- Make change, build, deploy to production server, load page, it gives error. Refresh browser, it works.
- Make change, build, deploy to production server, load page, it gives error. Refresh browser, it fails. Now it always fails.
- Make change, build, deploy to production server, load page, it magically works..

or:
- Make change, build, deploy to production server, load page, it fails. Try the same bundle locally on node server (without CDN), it works.

(mind you, all this time, it works just fine from the webpack dev-server!)

---

@niieani commented on [Sun Jul 17 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-233176788)

Sounds horrible indeed, I've personally not encountered it yet. Fortunately it seems, as a workaround, it's enough to try and build the site once again.

---

@sickboy commented on [Sun Jul 17 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-233176928)

@niieani neg, in the case of "always fails", depending on the next changes you'll make, it might work or not work the next time around. Also one can't really be sure that when it works, that it keeps working, and that it works for everyone, in every browser.

However my workaround of dropping the separate bundles and using a single bundle, seems to work for everyone, every time and every browser.

---

@niieani commented on [Thu Jul 21 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-234240924)

The Webpack team has announced they have fixed all of their unit tests in the most recent beta. Can you see if this still keeps happening?

---

@niieani commented on [Tue Jul 26 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-235116909)

Closing because I cannot reproduce with the latest version of Webpack 2. If this is still occurring for you @sickboy let me know.

---

@sickboy commented on [Sat Jul 30 2016](https://github.com/aurelia/skeleton-navigation/issues/613#issuecomment-236354161)

@niieani sadly the bug is back now when I have the CommonChunks plugin installed, and I even reproduced it in Dev mode now!

`Uncaught TypeError: Cannot read property 'call' of undefined`

```
    var action = new Promise(function (resolve, reject) {
      if (loaderPlugin) {
        try {
          return resolve(_this2.loaderPlugins[loaderPlugin].fetch(path));
        } catch (e) {
          return reject(e);
        }
      } else {
        try {
          var result = __webpack_require__(path);
          return _this2._getActualResult(result, resolve, reject);
        } catch (_) {}
        Promise.resolve().catch(function(err) { __webpack_require__.oe(err); }).then((function (require) {
          var result = __webpack_require__(441)("./" + path); // OFFENDING LINE
          return _this2._getActualResult(result, resolve, reject);
        }).bind(null, __webpack_require__));
      }
    }).then(function (result) {
```
Inside the webpack require, the modules[moduleId] is undefined:
```
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

The config workaround to fix it again:
```
        entry: {
          // workaround .call of undefined
          'app': coreBundles.aurelia.concat(['./src/main']),
        }
```

**Comment by niieani** [comment]
OK, I think I know how to fix this one.

**Comment by EisenbergEffect** [comment]
Status?

**Comment by niieani** [comment]
This will be fixed by the new Webpack stack, this is one of the more serious issues. I'll close this since the solution is tracked in https://github.com/aurelia/webpack-plugin/issues/67.
