### ISSUE TITLE
Webpack creating massive app.bundle

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/webpack-plugin#62]
When webpack bundles my solution it ends up including pretty much all of the node_modules folder which ends up being around 20MB i am not using like 85% of them?

**Comment by niieani** [comment]
That is very odd and shouldn't happen. Please post your webpack.config.js and package.json.

**Comment by devteamexpress** [comment]
{
  "name": "web-app",
  "version": "1.0.0",
  "main": "dist/main.js",
  "scripts": {
    "test": "cross-env NODE_ENV=test ./node_modules/karma/bin/karma start test/karma.conf.js",
    "webdriver:update": "cross-env ./node_modules/.bin/webdriver-manager update",
    "webdriver:start": "cross-env ./node_modules/.bin/webdriver-manager start",
    "pree2e": "npm run webdriver:update -- --standalone",
    "e2e": "concurrently --kill-others \"npm run e2e:start-when-ready\" \"cross-env WEBPACK_PORT=19876 npm start\"",
    "e2e:start-when-ready": "wait-on --timeout 20000 http-get://localhost:19876/index.html && npm run e2e:start",
    "e2e:start": "cross-env ./node_modules/.bin/protractor test/protractor.conf.js",
    "e2e:live": "npm run e2e:start -- --elementExplorer",
    "clean": "npm cache clean && rimraf node_modules test/coverage dist",
    "clean:dist": "rimraf dist",
    "preclean:install": "npm run clean",
    "clean:install": "npm set progress=false && npm install",
    "preclean:start": "npm run clean",
    "clean:start": "npm start",
    "watch": "npm run watch:dev",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch:prod": "npm run build:prod -- --watch",
    "build": "cross-env NODE_ENV=development npm run build:dev",
    "prebuild:dev": "npm run clean:dist",
    "build:dev": "cross-env NODE_ENV=development npm run webpack -- --progress --profile",
    "prebuild:prod": "npm run clean:dist",
    "build:prod": "cross-env NODE_ENV=production npm run webpack -- --progress --profile",
    "start": "npm run server:dev",
    "server": "npm run server:dev",
    "server:dev": "cross-env NODE_ENV=development node ./node_modules/webpack-dev-server/bin/webpack-dev-server --inline --progress --profile --watch",
    "server:dev:hmr": "npm run server:dev -- --hot",
    "server:prod": "http-server dist --cors",
    "webpack": "cross-env ./node_modules/.bin/webpack",
    "webpack-dev-server": "cross-env ./node_modules/.bin/webpack-dev-server"
  },
  "devDependencies": {
    "@easy-webpack/config-aurelia": "^2.0.1",
    "@easy-webpack/config-babel": "^2.0.2",
    "@easy-webpack/config-common-chunks-simple": "^2.0.1",
    "@easy-webpack/config-copy-files": "^1.0.0",
    "@easy-webpack/config-css": "^2.3.2",
    "@easy-webpack/config-env-development": "^2.1.1",
    "@easy-webpack/config-env-production": "^2.1.0",
    "@easy-webpack/config-external-source-maps": "^2.0.1",
    "@easy-webpack/config-fonts-and-images": "^1.2.1",
    "@easy-webpack/config-generate-index-html": "^2.0.1",
    "@easy-webpack/config-global-bluebird": "^1.2.0",
    "@easy-webpack/config-global-jquery": "^1.2.0",
    "@easy-webpack/config-global-regenerator": "^1.2.0",
    "@easy-webpack/config-html": "^2.0.2",
    "@easy-webpack/config-json": "^2.0.2",
    "@easy-webpack/config-test-coverage-istanbul": "^2.0.2",
    "@easy-webpack/config-uglify": "^2.1.0",
    "@easy-webpack/core": "^1.3.2",
    "aurelia-tools": "^0.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-syntax-flow": "^6.5.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-modules-amd": "^6.6.5",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.7.7",
    "babel-plugin-transform-es2015-modules-systemjs": "^6.6.5",
    "babel-plugin-transform-flow-strip-types": "^6.7.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-es2015-loose-native-modules": "^1.0.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-register": "^6.11.6",
    "concurrently": "^2.2.0",
    "cross-env": "^2.0.0",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.4.1",
    "protractor": "^4.0.0",
    "rimraf": "^2.5.4",
    "wait-on": "^1.5.2",
    "webpack": ">=2.1.0-beta.13 || ^2.1.0",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": ">=2.1.0-beta.0 || ^2.1.0"
  },
  "dependencies": {
    "aurelia-bootstrapper-webpack": "^1.0.0",
    "aurelia-event-aggregator": "^1.0.0",
    "aurelia-framework": "^1.0.0",
    "aurelia-history-browser": "^1.0.0",
    "aurelia-loader-webpack": "^1.0.0",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-pal-browser": "^1.0.0",
    "aurelia-polyfills": "^1.0.0",
    "aurelia-route-recognizer": "^1.0.0",
    "aurelia-router": "^1.0.2",
    "aurelia-templating-binding": "^1.0.0",
    "aurelia-templating-resources": "^1.0.0",
    "aurelia-templating-router": "^1.0.0",
    "aurelia-animator-css": "^1.0.0",
    "aurelia-binding": "^1.0.0",
    "aurelia-bootstrapper": "^1.0.0",
    "aurelia-dependency-injection": "^1.0.0",
    "aurelia-dialog": "^1.0.0-beta.3.0.0",
    "aurelia-history": "^1.0.0",
    "aurelia-logging": "^1.0.0",
    "aurelia-metadata": "^1.0.0",
    "aurelia-pal": "^1.0.0",
    "aurelia-path": "^1.0.0",
    "aurelia-task-queue": "^1.0.0",
    "aurelia-templating": "^1.0.0",
    "aurelia-validation": "^0.11.0",
    "jquery": "^2.2.0",
    "moment": "^2.11.2",
    "rome": "2.1.22",
    "underscore": "^1.8.3",
    "isomorphic-fetch": "^2.2.1",
    "bluebird": "^3.4.1",
    "compression": "^1.2.0",
    "ect": "*",
    "express": "4.x",
    "less-middleware": "*",
    "request": "^2.69.0",
    "require-dir": "^0.3.0",
    "ua-parser2": "^0.1.34"
  },
  "aurelia": {
    "build": {
      "resources": []
    }
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-1"
    ],
    "plugins": ["add-module-exports"]
  }
}

**Comment by devteamexpress** [comment]
"use strict";

/**
 * To learn more about how to use Easy Webpack
 * Take a look at the README here: https://github.com/easy-webpack/core
 **/
const easyWebpack = require('@easy-webpack/core');
const generateConfig = easyWebpack.default;
const webpack = require('webpack');
const get = easyWebpack.get;
const path = require('path');
const ENV = process.env.NODE_ENV && process.env.NODE_ENV.toLowerCase() || 'development';
let config;
// basic configuration:
const title = 'web-app';
const baseUrl = '/';
const rootDir = path.resolve();
const srcDir = path.resolve('src');
const outDir = path.resolve('dist');

const coreBundles = {
  bootstrap: [
    'aurelia-bootstrapper-webpack',
    'aurelia-polyfills',
    'aurelia-pal',
    'aurelia-pal-browser',
    'regenerator-runtime'
  ],
  // these will be included in the 'aurelia' bundle (except for the above bootstrap packages)
  aurelia: [
    'aurelia-animator-css',
    'aurelia-bootstrapper-webpack',
    'aurelia-binding',
    'aurelia-dependency-injection',
    'aurelia-event-aggregator',
    'aurelia-framework',
    'aurelia-history',
    'aurelia-history-browser',
    'aurelia-loader',
    'aurelia-loader-webpack',
    'aurelia-logging',
    'aurelia-logging-console',
    'aurelia-metadata',
    'aurelia-pal',
    'aurelia-pal-browser',
    'aurelia-path',
    'aurelia-polyfills',
    'aurelia-route-recognizer',
    'aurelia-router',
    'aurelia-task-queue',
    'aurelia-templating',
    'aurelia-templating-binding',
    'aurelia-templating-router',
    'aurelia-templating-resources',
    'aurelia-validation',
    'aurelia-dialog',
  ]
}

const baseConfig = {
  plugins:[

  ],
  loaders: [
    { test: /aurelia-dialog(\\|\/)dist(\\|\/)commonjs(\\|\/)dialog\.css/, loader: 'raw' },
    { test: /\.css$/, exclude: /aurelia-dialog(\\|\/)dist(\\|\/)commonjs(\\|\/)dialog\.css/, loader: 'style!css' }
  ],
  resolve: {
    alias: {
        rome: path.join(__dirname, 'lib/rome/rome.standalone.min'),
        slickjs: path.join(__dirname, 'lib/slick/slick.min'),
        tooltipsy: path.join(__dirname, 'lib/tooltipsy/tooltipsy.min'),
        zoom: path.join(__dirname, 'lib/zoom/zoom'),
        realtime: path.join(__dirname, 'lib/realtime/realtime'),
        ddslick: path.join(__dirname, 'lib/ddd/jquery.ddslick.min')

    }
  },
  entry: {
    'app': [/* this is filled by the aurelia-webpack-plugin */],
    'aurelia-bootstrap': coreBundles.bootstrap,
    'aurelia': coreBundles.aurelia.filter(pkg => coreBundles.bootstrap.indexOf(pkg) === -1)
  },
  output: {
    path: outDir
  }
}

// advanced configuration:
switch (ENV) {
  case 'production':
    config = generateConfig(
      baseConfig,

      require('@easy-webpack/config-env-production')
        ({compress: true}),
        
      require('@easy-webpack/config-aurelia')
        ({root: rootDir, src: srcDir, title: title, baseUrl: baseUrl}),

      require('@easy-webpack/config-babel')(),
      require('@easy-webpack/config-html')(),

      require('@easy-webpack/config-css')
        ({ filename: 'styles.css', allChunks: true, sourceMap: false }),

      require('@easy-webpack/config-fonts-and-images')(),
      require('@easy-webpack/config-global-bluebird')(),
      require('@easy-webpack/config-global-jquery')(),
      require('@easy-webpack/config-global-regenerator')(),
      require('@easy-webpack/config-generate-index-html')
        ({minify: true}),

      require('@easy-webpack/config-copy-files')
        ({patterns: [{ from: 'favicon.ico', to: 'favicon.ico' }]}),

      require('@easy-webpack/config-common-chunks-simple')
        ({appChunkName: 'app', firstChunk: 'aurelia-bootstrap'}),

      require('@easy-webpack/config-uglify')
        ({debug: false})
    );
    break;
  
  case 'staging':
    config = generateConfig(
      baseConfig,

      require('@easy-webpack/config-env-development')
        ({devtool: 'inline-source-map'}),

      require('@easy-webpack/config-aurelia')
        ({root: rootDir, src: srcDir, title: title, baseUrl: baseUrl}),

      require('@easy-webpack/config-babel')(),
      require('@easy-webpack/config-html')(),

      require('@easy-webpack/config-css')
        ({ filename: 'styles.css', allChunks: true, sourceMap: false }),

      require('@easy-webpack/config-fonts-and-images')(),
      require('@easy-webpack/config-global-bluebird')(),
      require('@easy-webpack/config-global-jquery')(),
      require('@easy-webpack/config-global-regenerator')(),
      require('@easy-webpack/config-generate-index-html')(),

      require('@easy-webpack/config-test-coverage-istanbul')()
    );
    break;
  
  default:
  case 'development':
    config = generateConfig(
      baseConfig,

      require('@easy-webpack/config-env-development')(),     

      require('@easy-webpack/config-aurelia')
        ({root: rootDir, src: srcDir, title: title, baseUrl: baseUrl}),

      require('@easy-webpack/config-babel')(),
      require('@easy-webpack/config-html')(),

      require('@easy-webpack/config-css')
        ({ filename: 'styles.css', allChunks: true, sourceMap: false }),

      require('@easy-webpack/config-fonts-and-images')(),
      require('@easy-webpack/config-global-bluebird')(),
      require('@easy-webpack/config-global-jquery')(),
      require('@easy-webpack/config-global-regenerator')(),
      //require('@easy-webpack/config-external-source-maps')(),      

      require('@easy-webpack/config-copy-files')
        ({patterns: [{ from: 'favicon.ico', to: 'favicon.ico' }]}),

      require('@easy-webpack/config-common-chunks-simple')
        ({appChunkName: 'app', firstChunk: 'aurelia-bootstrap'})
    );    
    break;
}

module.exports = config;

**Comment by devteamexpress** [comment]
For example ua-parser-2 ends up in there, even though it's no where in my aurelia application , i use it as part of a node express server i'm running.

**Comment by niieani** [comment]
Yeah, the webpack-plugin by default makes `main`s of all the `dependencies` listed in `package.json` available to Aurelia. I'll make that behavior optional in a future release. 
But I think you should have two separate projects for the frontend and backend. Things like `express` and `ua-parser-2` don't belong in a frontend project. Alternatively you can move those to `devDependencies`.

**Comment by devteamexpress** [comment]
Thanks so much
