### ISSUE TITLE
Images referenced in index.html not included in build

### ISSUE THREAD

**Issue by wichert** [aurelia/webpack-plugin#63]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.3.0

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
web pack 2.1.0-beta.20

* **Browser:**
all

* **Language:**
all 

**Current behavior:**

I added a logo to the splash in index.html:

```html
    <div class="splash">
      <img src="src/assets/images/logo-curvetips.png" alt="">
      <div class="message"><%- webpackConfig.metadata.title %></div>
      <i class="fa fa-spinner fa-spin"></i>
    </div>
```

After doing `npm run build` or `npm run build:prod` the logo is not included in the generated list. This results in an missing-image placeholder being shown on the page while aurelia is loading.

**Expected/desired behavior:**

I would expect the logo to be copied to `dist/` and renamed to <hash>.png .

**Comment by icanhasjonas** [comment]
Hello

In your configuration, you probably reference `index.html` from the `HtmlWebpackPlugin`. Just make sure you have a loader for your `html` files, or specifically for your `index.html` file and it should work fine.

Here's an example:

```js
		loaders: [
			{
				test: /index\.html$/,
				loader: 'html',
				query: {
					interpolate: true,
					minimize: false,
					attrs: ["img:src", "link:href"]
				}
			}
		]
```

**Comment by wichert** [comment]
@icanhasjonas I use the [webpack.config.js from the esnext-webpack skeleton](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext-webpack/webpack.config.js), which uses a lot of magic to generate the config. I can't easily tell what part of that would be responsible for loader config. Perhaps `aurelia-loader-webpack` ?

**Comment by niieani** [comment]
Actually, the html loader is used in that config. However `index.html` is generated by a separate plugin, thus there's no interpolation done. I'll look into that.

**Comment by wichert** [comment]
`index.js` is generated, but `index.html` is not.

**Comment by wichert** [comment]
Ignored that - I was wrong. `index.html` is generated (or perhaps interpolated is the better term here?).

**Comment by niieani** [comment]
@wichert not sure if it's currently possible to use loaders as post-processors with the HtmlWebpackPlugin.
Try opening an issue here: https://github.com/ampedandwired/html-webpack-plugin referencing this one so we can track.

**Comment by wichert** [comment]
I was thinking: isn't this a situation where you would want to chain the loaders used for index.html, instead of using a post-processor? Similar to how for SASS files you use something like `['scss', 'css']` you would use `['generator', 'html']` here?

**Comment by niieani** [comment]
@wichert the thing is the HtmlWebpackPlugin is not a loader, but a plugin. Not sure how to accomplish what you desire here. Perhaps simply copy the image asset using the WebpackCopyPlugin?
