### ISSUE TITLE
Webpack HMR not working anymore

### ISSUE THREAD

**Issue by niieani** [aurelia/webpack-plugin#65]
@mgerwinn commented on [Fri Jul 29 2016](https://github.com/aurelia/skeleton-navigation/issues/629)

**I'm submitting a bug report**
- **Aurelia Skeleton Version**
  skeleton-esnext-webpack
- **Framework Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.x
- **Node Version:**
  6.3.1
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.20
- **Browser:**
  all
- **Language:**
  all | TypeScript X.X | ESNext

**Current behavior:**
Running npm server:dev:hmr is starting webpack with hmr enabled.
Every change in the source folder is triggering a recompile correctly. Anyhow the browser is not picking up the changes and showing this error message instead:
![image](https://cloud.githubusercontent.com/assets/836048/17239566/4542fe5e-5565-11e6-96a6-fdc8f6d12d03.png)
So actually module.hot is not defined.

---

@niieani commented on [Fri Jul 29 2016](https://github.com/aurelia/skeleton-navigation/issues/629#issuecomment-236136625)

Note that HMR only works for CSS at this point. It's not yet implemented in Aurelia. Anyway, this looks like a Webpack bug, not related to Aurelia. 

---

@mgerwinn commented on [Fri Jul 29 2016](https://github.com/aurelia/skeleton-navigation/issues/629#issuecomment-236175213)

Thanks for the response. Of course it's only working for css atm. Thats fine and it has worked before (e.g. aurelia-skeleton-navigation-webpack 1.0.0-beta.2.0.0).
Now its not working anymore.

I don't see any difference in the package.json for webpack or webpack-dev-server defined versions. So I do assume their is a side effect from an updated aurelia version. Or any other dependency in the starter kit that updated.

Would be great if someone can confirm, having the same issues with the latest skeleton (1.0.0)
or having a fix for it.

---

@niieani commented on [Fri Jul 29 2016](https://github.com/aurelia/skeleton-navigation/issues/629#issuecomment-236180029)

Try `npm update`, we pushed out some fixes to the webpack-plugin, see if that has anything to do with it.

---

@mgerwinn commented on [Fri Jul 29 2016](https://github.com/aurelia/skeleton-navigation/issues/629#issuecomment-236202075)

Unfortunately the issue is still present after npm update. Anything else I can try?

---

@niieani commented on [Fri Jul 29 2016](https://github.com/aurelia/skeleton-navigation/issues/629#issuecomment-236209666)

I'm a bit at a loss. Looks like a Webpack bug to me, since it's coming from `dev-server.js`. One thing you could try is passing `nameExternalModules: false, nameLocalModules: false` to the Aurelia webpack plugin. But I don't think it's going to help.

---

@niieani commented on [Fri Jul 29 2016](https://github.com/aurelia/skeleton-navigation/issues/629#issuecomment-236210341)

Note that Easy Webpack doesn't yet support those parameters. I'll push an update soon, but for now you could try using the plugin directly.

---

@mgerwinn commented on [Fri Jul 29 2016](https://github.com/aurelia/skeleton-navigation/issues/629#issuecomment-236242621)

Nope. Still the same issue. I definitely agree to your argumentation that its more related to webpack than aurelia. But still the version from webpack and webpack-dev-server is untouched  from the working version(1.0.0-beta.2.0.0) to the current one (1.0.0).

---

@mgerwinn commented on [Mon Aug 01 2016](https://github.com/aurelia/skeleton-navigation/issues/629#issuecomment-236699838)

So at least I figured out the source of the issue. Its related to this commit: https://github.com/aurelia/webpack-plugin/commit/54d7c65
Line 173 is missing "hot" variable declaration which is present in "normal-module-loader". 
Just adding the hot variable is bringing back HMR like behaviour. Still css injection is not working anymore. So we're sticking with "aurelia-webpack-plugin": "1.0.0-beta.4.0.1" for now.

**Comment by niieani** [comment]
Thanks for finding out the reasons, I'll try to figure out the best way to fix this.

**Comment by MrHayato** [comment]
I've gotten this to work in our project using a plugin. It seems the problem is because [this line](https://github.com/aurelia/webpack-plugin/blob/master/src/index.js#L175) is missing the hot module calls. In our webpack configuration, we created a new plugin:

```

class AureliaHotModulePlugin {
    apply(compiler) {
        compiler.plugin('compilation', function (compilation) {
            // Re-add HMR functionality, aurelia plugin removes it.
            compilation.mainTemplate.plugin('require', function(source) {
                return source.replace(`exports: {}`, this.asString([
                    "exports: {},",
                    "hot: hotCreateModule(moduleId),",
                    "parents: (hotCurrentParentsTemp = hotCurrentParents, hotCurrentParents = [], hotCurrentParentsTemp),",
                    "children: []"
                ]));
            });
        });
    }
}
```
and added it to our config's plugins list (making sure that it appears after the AureliaWebpackPlugin). This makes HMR "work" for us again (not full HMR, but at least no more `module.hot` errors and sass can still hot reload)

**Comment by niieani** [comment]
Yes, thanks for the workaround @MrHayato.
What I need to do to fix this is https://github.com/aurelia/webpack-plugin/issues/67 - change the way the __webpack_require__ (mainTemplate) is hooked, so that it's not completely replaced, but extends the original code (which might be hooked by additional plugins).

**Comment by jinwangchina** [comment]
Does the "skeleton-typescript-webpack" support full HMR (not just CSS) now? 

I found the plugin below, looks like it supports full HMR, but not sure if it is in the skeleton now, as I still get error "dev-server.js:44 Uncaught TypeError: Cannot read property 'status' of undefined".
https://github.com/aurelia/hot-module-reload

**Comment by niieani** [comment]
@jinwangchina support for hot-module-reload is not merged in the skeleton repo yet. See https://github.com/aurelia/skeleton-navigation/issues/714.

**Comment by niieani** [comment]
Fixed by https://github.com/aurelia/skeleton-navigation/pull/714
