### ISSUE TITLE
aurellia-framework module not loaded

### ISSUE THREAD

**Issue by alejodev76** [aurelia/webpack-plugin#66]
**I'm submitting a bug report**

* **Library Version:**
aurelia-webpack-plugin-1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.1

* **NPM Version:**
3.9.3

* **JSPM OR Webpack AND Version**
webpack 1.13.1

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I updated my Aurelia project  and all its modules to the latest version (1.0.0) including aurelia-webpack-plugin from 1.0.0-beta.4.0.0 to 1.1.0 and a few things stopped working:

1.  ExtractText plugin is not extracting the css into a file, it creates the file but leaves it empty.
2. My application loads an empty page because the aurelia-framework module is not loaded correctly and noticed that on line 67 of aurelia-loader-webpack (pasted below) m is an empty object when returned.

const loader = new WebpackLoader();
    loader.loadModule('aurelia-framework').then( function(m => {
      Aurelia = m.Aurelia;
      for (let i = 0, ii = appHost.length; i < ii; ++i) {
        handleApp(loader, appHost[i]).catch(console.error.bind(console));
      }

      sharedLoader = loader;
      for (let i = 0, ii = bootstrapQueue.length; i < ii; ++i) {
        bootstrapQueue[i]();
      }
      bootstrapQueue = null;
    })

after reverting back aurelia-webpack-plugin 1.0.0-beta.4.0.0 the problems went away.

**Comment by niieani** [comment]
Webpack 1 is not supported. Please use Webpack 2.1.0.beta. 
Feel free to submit a Pull Request with support for Webpack 1 though, we'll accept.
