### ISSUE TITLE
Improve hooking __webpack_require__ module loader

### ISSUE THREAD

**Issue by niieani** [aurelia/webpack-plugin#67]
Needed to fix #65, #61, #73.

**Comment by niieani** [comment]
Reference: https://github.com/webpack/webpack/blob/1675a5a5ca42cc6d9358f8fa4f283619503fa2c0/lib/HotModuleReplacementPlugin.js#L188-L195

**Comment by mikeesouth** [comment]
@niieani any status update here?

**Comment by niieani** [comment]
Yes, the 2.0 version of webpack-plugin solves this, as it doesn't create the hook anymore. Please migrate to the new version if this is a problem for you.

**Comment by niieani** [comment]
Fixed by https://github.com/aurelia/skeleton-navigation/pull/714
