### ISSUE TITLE
Build fails when main of a dependency points to a non-JS file

### ISSUE THREAD

**Issue by niieani** [aurelia/webpack-plugin#71]
@istrau2 commented on [Mon Aug 08 2016](https://github.com/aurelia/skeleton-navigation/issues/640)

Here are the steps I took:

1) Downloaded the skeleton
2) Ran 'npm run build:prod'
3) Ran 'npm run server:prod'
4) Opened up localhost:8080

I get an error:

Uncaught TypeError: Cannot read property 'call' of undefined

---

@niieani commented on [Mon Aug 08 2016](https://github.com/aurelia/skeleton-navigation/issues/640#issuecomment-238172240)

Your OS? Node and NPM version? Use the issue template next time, please.

---

@istrau2 commented on [Wed Aug 10 2016](https://github.com/aurelia/skeleton-navigation/issues/640#issuecomment-238745158)

@niieani Sorry for the late response. I actually went back over my actions and realized that I had actually included some dependencies. After a bunch of iteration, I have finally figured out what caused the build to fail (mind you this is only for build:prod, dev build works fine). The following entry in package.json caused the build to fail:

```
"dependencies: {
    "bootstrap-social": "^5.0.0",   
}
```

I have no idea why. Could it be because the main entry in that package's package.json points to a css file?

I am using
Windows 10
node 6.3.1
npm 3.10.3

---

@niieani commented on [Wed Aug 10 2016](https://github.com/aurelia/skeleton-navigation/issues/640#issuecomment-238814959)

> Could it be because the main entry in that package's package.json points to a css file?

Yes, that could cause the build to fail. We can try to add a safety mechanism into webpack-plugin, but `main` should never point to a `css`, it looks like a bug of `bootstrap-social` (feel free to file the bug at its repo too). For now, put that dependency into `devDependencies`.

**Comment by EisenbergEffect** [comment]
@niieani Status on this?

**Comment by niieani** [comment]
Will be resolved by the new Webpack plugin architecture.

**Comment by niieani** [comment]
Fixed by https://github.com/aurelia/skeleton-navigation/pull/714
