### ISSUE TITLE
Multiple CSS entry points get same output when using ExtractTextPlugin

### ISSUE THREAD

**Issue by Andreas-Hjortland** [aurelia/webpack-plugin#73]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10, also reproduced under arch linux

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
webpack 1.13.1

* **Browser:**
all

* **Language:**
CSS

**Current behavior:**
When I use the extract-text-plugin in conjuction with the webpack plugin and have defined multiple entry points with different stylesheets, I get the same output stylesheet for all the entry points. I have not understood exactly which stylesheet which is selected.

**Expected/desired behavior:**

* **What is the expected behavior?**

When I have multiple entrypoints with different stylesheets I expected that the output-stylesheets should be different as well. 

Unfortunately since this is a build-process bug, it is not possible to use the runnable gist, but I have created a git-repository which reproduces the issue at [https://github.com/Andreas-Hjortland/aurelia-webpack-issue](https://github.com/Andreas-Hjortland/aurelia-webpack-issue). The master branch uses version 1.1.0 which has the problem. In the fix-issue branch I use a [fork](https://github.com/Andreas-Hjortland/webpack-plugin) of the webpack-plugin where I have deleted the offending code. Unfortunately I don't completely understand what the code does or why it is there, so I didn't want to create a pull request for it.

* **What is the motivation / use case for changing the behavior?**
The motivation is that I want to use the extract-text-plugin use css in the head-tag so that the styles work properly on load instead of using javascript to set the styles, but that is impossible when we have multiple entry-points at the moment

* **Has it worked in previous versions?**
It worked in version 1.0.0-beta.4.0.1

**What I have done to debug the issue**
I forked the plugin and tried to revert changes between 1.1.0 and 1.0.0beta.4.0.1 until I discovered which commit was causing this behavior. I discovered that the issue was in the commit [54d7c65 (feat(all): use path-based moduleIds and hook native __webpack_require__)](https://github.com/aurelia/webpack-plugin/commit/54d7c655fca9df55a6425488fbcdef9ccac4a8de). And more specifically the [customWebpackRequire()](https://github.com/aurelia/webpack-plugin/commit/54d7c655fca9df55a6425488fbcdef9ccac4a8de#diff-1fdf421c05c1140f6d71444ea2b27638R164) function.

**Comment by Andreas-Hjortland** [comment]
I forgot to add. To build the repository which shows the bug, you need to run `npm install` followed by `npm run build`. 

If you check the dist folder you will see that the content of frame.css and app.css is the same even though the source files (frame.less and style.less) is different.

**Comment by Andreas-Hjortland** [comment]
I also discovered that you might need to manually remove the `node_modules/aurelia-webpack-plugin` folder when changing branch in the aurelia-webpack-issue repository in order to force npm to download the new package.

**Comment by fmal** [comment]
+1 I am having the same issue, very frustrating.

**Comment by Andreas-Hjortland** [comment]
@fmal If you just want it working until we have a proper fix, you can use my fork for the aurelia-webpack-plugin. Just set the version of `aurelia-webpack-plugin` to `"andreas-hjortland/webpack-plugin#master"`

**Comment by EisenbergEffect** [comment]
@niieani Please take a look at this. It has been sitting here with no response for too long.

**Comment by niieani** [comment]
Tracking the problem in https://github.com/aurelia/webpack-plugin/issues/73. Closing as duplicate.
