### ISSUE TITLE
webpack fails with <require from=""> module syntax unless also in js files

### ISSUE THREAD

**Issue by deitch** [aurelia/webpack-plugin#8]
I install bootstrap via npm and then try to use the template's `<require>` syntax:

````html
  <require from="bootstrap/css/bootstrap.min.css"></require>
````

The above will fail in webpack but will work in jspm. It only works if I include it in a JS file:

````javascript
import 'bootstrap/dist/css/bootstrap.css';
````

Stepping through the code in Chrome debugger, aurelia-templating successfully finds the require and tries to load it from the bundle, but the bundle does not contain it.

It appears to be an issue with parsing the html template during *bundle* time (as opposed to run-time).

Be happy to try and help with a fix if someone could explain why this fails and how it works in jspm?

**Comment by Jaans** [comment]
FWIW, I found the following to work for me:

### For CSS that is located outside /src/ path
E.g. `bootstrap` / `font-awsome` that is not part of Aurelia, I use the following from code (.js / .ts)

```
import "../node_modules/bootstrap/dist/css/bootstrap.css";
import "../node_modules/font-awesome/css/font-awesome.css";
import "../styles/index.css";
```
_And set webpack to use the following loader: `{ test: /\.css$/, exclude: /src/, loader: 'style-loader!css-loader' }`_


### For CSS that is located inside /src/ path
E.g. View/ViewModel pair specific styles or other shared styles even, I use the below in a view template (.html)
```
<require from="Shared/Styles/app.css"></require>
<require from="Shared/nav-bar.html"></require>
```
_And set webpack to use the following loader: `{ test: /\\src\\.*\.css$/, loader: 'raw-loader' }` // Only those within src._

_**Note:** The above regular expression is Windows specific (backslashes) so adjust if necessary._

It's worth mentioning that somewhere I had read that with the Aurelia loader integration with webpack, it needs CSS and HTML <requires /> to use the `!raw-loader`.

### Hot Loading
What is unfortunate at this stage is that using the raw-loader means that we don't have hot-loading of Views / CSS loaded with it. It does however work for those loaded outside the /src/ folder with `style!css` loaders.

Hope that helps.

**Comment by deitch** [comment]
Hey @Jaans thanks for the suggestions. So basically you are saying, it can reasonably handle stuff that is in `./src/`, but if it comes from outside it - like npm - then it doesn't do it correctly.

The problem, I think, is that webpack itself doesn't know to parse `<require from...>` so it never loads the modules. It does it correctly for JS `import` but not html `<require>`, so it ends up with the CSS from JS in its bundle, but not the CSS from html. 

I think this needs to be fixed at the `AureliaWebpackPlugin` level, but good to have comment from one of the maintainers?

**Comment by mirronelli** [comment]
see my comment on #14 
unless the bundler sees a "./" before the target in require it does not include it
change 
`<require from="/some.css"></require>`
to
`<require from="./some.css"></require>`

**Comment by deitch** [comment]
@mirronelli so if I add the explicit bathing of `'./` it works? I will have to try it. Thank you.

**Comment by deitch** [comment]
@mirronelli nope. That is it is *inside* `src/`, hence `./` works. If it is *outside* `src/`, e.g. included via npm, then it doesn't do it correctly. This remains a bug.

**Comment by mirronelli** [comment]
If you have context set to "src" you need to use "../" to correctly reference to node modules. It works for me.

**Comment by deitch** [comment]
@mirronelli you lost me. You are saying I *can* reference css files inside node_modules if I do the following:

````html
<!--DOES NOT WORK -->
<require from="bootstrap/css/bootstrap.min.css"></require>

<!-- SHOULD WORK?? -->
<require from="../node_modules/bootstrap/css/bootstrap.min.css"></require>
````

I thought it was a problem at the time of creating the bundle?

**Comment by EisenbergEffect** [comment]
Fixed in https://github.com/aurelia/skeleton-navigation/commit/1df111d47cd5303af7442b3152dc4201be4ffbf9

**Comment by deitch** [comment]
Thanks @EisenbergEffect, hats off.

Is this getting bundle in production package?

**Comment by EisenbergEffect** [comment]
Definitely all thanks go to @niieani He did amazing work.
It's on master now. We'll push the release out soon. @niieani can answer any questions you have over specifics.

**Comment by deitch** [comment]
Was the analysis correct? Was it the bundle time parsing?

If I had the time, would have been happy to figure it out, create a PR, but got to deal with clients, right? :-)

**Comment by niieani** [comment]
@deitch the reason was that there was **no** bundle-time parsing performed of Views. It is implemented now.

**Comment by deitch** [comment]
Ah, like I had thought when digging through the source.

Thanks.
