### ISSUE TITLE
Module Resolve Aliases supported?

### ISSUE THREAD

**Issue by jawa-the-hutt** [aurelia/webpack-plugin#80]
Does the plugin currently support resolve aliases?  If I understand #53 correctly, it appears to say that it does not.  I've got a current use case that I think would be solved by this, but not for sure.

Trying to get the aurelia-interactjs plugin (https://github.com/eriklieben/aurelia-interactjs) working with webpack and I think the issue is because the ultimate source library, http://interactjs.io, that the plugin is trying to wrap just hasn't done a very good job of being packaged correctly 

It appears from the aurelia-interactjs plugin readme that jspm handles interact.js just fine, but the Aurelia CLI needs some additional configuration which appears to be aliasing things to get it working.  To date, I've not been able to get figure out how to get webpack to handle it so that I'm able to call the main `interact` function.  It just doesn't recognize it as a valid function.

I guess it's possible my issue with the plugin is not alias related but some other thing entirely that's preventing me from getting aurelia to recognize the interact.js library.  So, I would appreciate any advice you might have down that side of things if you think it's warranted.

**Comment by niieani** [comment]
Resolve Aliases are not yet supported. The will be supported by the next major version of the plugin though, because it will use Webpack's internal resolving mechanism.

**Comment by MeirionHughes** [comment]
supported in 2.0.0-rc.1. I have it working in [my example plugin](https://github.com/MeirionHughes/aurelia-plugin-skeleton/blob/master/webpack.config.js#L18-L20)

**Comment by jods4** [comment]
Please note that 2.0.0 is not an enhancement of 1.x but a new set of plugins that will require a few changes in your project.
