### ISSUE TITLE
webpack not loading aurelia-auth

### ISSUE THREAD

**Issue by kingsleyh** [aurelia/webpack-plugin#81]
when using the aurelia skeleton - webpack typescript - it does not load aurelia-auth properly. 

I followed all the instructions for aurelia-auth but still it seems like FetchConfig is not being loaded from aurelia-auth.

    Property 'fetchConfig' does not exist on type 'App'.

I believe it should work so either this issue is in aurelia-auth or in this project - and considering it looks like the dependency is not being loaded - I suspect some incompatibility between these 2 projects.

any help greatly appreciated.

**Comment by niieani** [comment]
Can you provide a link to aurelia-auth? Most probably a bug or omission on thier part.

**Comment by kingsleyh** [comment]
Hi yes here you go:   https://github.com/paulvanbladel/aurelia-auth

**Comment by niieani** [comment]
@kingsleyh here you go, prepared a PR: https://github.com/paulvanbladel/aurelia-auth/pull/166

**Comment by niieani** [comment]
for now you can just add the resource locally to your own package.json, but specify together with the package name, `aurelia-auth/auth-filter`
