### ISSUE TITLE
Empty bundle with Webpack 2. Docs?

### ISSUE THREAD

**Issue by jods4** [aurelia/webpack-plugin#83]
I wanted to give Aurelia a try with Webpack, but I couldn't get it working.
I'm using Webpack 2 (is that supported?).
I am doing everything from scratch and without easy-webpack as I like to understand how things work and have some fine control.

This doc [Using normal webpack](https://github.com/bigopon/framework/blob/e44fcbd1cfe62a65a4331ae4b7b63e0c833c347e/doc/article/en-US/setup-webpack.md#using-normal-webpack-configuration) was the best info I found. It references `webpack@2.1-beta.25` so I figured it ought to work.

Note that the doc says this:
```js
      entry: {
          'app': [], // <-- this array will be filled by the aurelia-webpack-plugin
```
But webpack reports an error if you leave `app` empty. What should we put there?

Then my understanding from the docs was that with the aurelia-webpack plugin, everything inside `./src` would be automatically included in the bundle. This is not happening. I have just a single view to test out webpack, but the bundle stays very empty, no matter what.

Looking at debug traces I can see that the plugin _is_ running.
I've looked at the source code to try to understand why it did not include my files, but I honestly couldn't figure out where it was supposed to add them... How is that supposed to work? Is there something special I should be doing in addition to running `aurelia-webpack-plugin` to see my files in the bundle?

My templates are `.html` and view models `.ts` if that makes a difference (I have webpack properly set up with TS loader).

**Comment by EisenbergEffect** [comment]
Webpack has been having a lot of breaking changes. We're working on some major updates ourselves at the moment. Perhaps @niieani can comment on this.

**Comment by jods4** [comment]
@niieani any status please? 
I would like to know what the current status is, if there are any short-term plans and possibly help make it work if it doesn't.

**Comment by jods4** [comment]
OK I found this: aurelia/skeleton-navigation#714
Since this plugin is going to disappear I'm closing this ticket and I'll experiment with the new way.
At first glance I shall say that I like the approach a lot more.

**Comment by niieani** [comment]
Sorry about not replying here, I only now got to this issue on my backlog.
