### ISSUE TITLE
Webpack build fails when view contains custom element or compose element

### ISSUE THREAD

**Issue by jithinoj** [aurelia/webpack-plugin#85]
We have created application using aurelia+webpack.Webpack build(both development and production) process is failed when page is using a custom element or compose element. If we remove these elements from the view , the webpack build process is success. 

package.json

`{
  "name": "webpack-and-aurelia",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "You",
  "license": "ISC",
  "dependencies": {
    "aurelia-bootstrapper-webpack": "^1.0.0",
    "aurelia-event-aggregator": "^1.0.0",
    "aurelia-framework": "^1.0.1",
    "aurelia-history-browser": "^1.0.0",
    "aurelia-loader-webpack": "^1.0.3",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-templating-binding": "^1.0.0",
    "aurelia-templating-resources": "^1.0.0",
    "aurelia-templating-router": "^1.0.0"
  },
  "devDependencies": {
    "@types/node": "^6.0.52",
    "aurelia-webpack-plugin": "^1.1.0",
    "bluebird": "^2.9.2",
    "html-loader": "^0.4.3",
    "source-map-loader": "^0.1.5",
    "toastr": "^2.1.2",
    "ts-node": "^1.7.2",
    "webpack": "^1.14.0"
  }

}
`

tsconfig.json

`{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "amd",  
    "experimentalDecorators": true,   
    "moduleResolution": "node",
    "sourceMap": false,   
    "allowSyntheticDefaultImports": true,
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true
  },
  "exclude": [
    "node_modules",
    "build"
  ]
}
`

webpack.config.js

`var AureliaWebPackPlugin = require('aurelia-webpack-plugin');
var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: {     
        'app': [],   
        'aurelia': [
            'aurelia-bootstrapper-webpack',
            'aurelia-polyfills',
            'aurelia-pal',
            'aurelia-pal-browser',
            'aurelia-binding',
            'aurelia-dependency-injection',
            'aurelia-event-aggregator',
            'aurelia-framework',
            'aurelia-history',
            'aurelia-history-browser',
            'aurelia-loader',
            'aurelia-loader-webpack',
            'aurelia-logging',
            'aurelia-logging-console',
            'aurelia-metadata',
            'aurelia-path',
            'aurelia-route-recognizer',
            'aurelia-router',
            'aurelia-task-queue',
            'aurelia-templating',
            'aurelia-templating-binding',
            'aurelia-templating-router',
            'aurelia-templating-resources'
        ]
    },
   
    output: {     
        path: './build',
        filename: '[name].bundle.js',
        sourceMapFilename: '[name].bundle.js.map'
    },  
    module: {
        preLoaders: [
            {
                test: /\.js$/,
                exclude: path.resolve('node_modules/aurelia-webpack-plugin'),
                loader: "source-map-loader"
            }
        ],
        loaders: [          
            { test: /\.html$/, loader: 'html', exclude: path.resolve('src/index.html') }
        ]

    },
    plugins: [      
        new AureliaWebPackPlugin(),     
       new webpack.optimize.CommonsChunkPlugin({ name: ['aurelia'] })        
    ],
  
};`

The view which webpack build process is failed(app.html)

    <require  from="./custom-component"></require>   
    <custom-component></custom-component>

The webpack task runner showing following error

WARNING in ./src/app/custom-component.ts
Module parse failed: C:\Users\Developer\documents\visual studio 2017\Projects\WebpackSample\WebpackSample\src\app\custom-component.ts Unexpected token (2:11)
You may need an appropriate loader to handle this file type.

**Comment by niieani** [comment]
You have a `custom-component.ts` yet no loader for TypeScript files. This is a Webpack configuration problem, not related to the Aurelia plugin.

**Comment by jithinoj** [comment]
But my typescript build target configuration is es5. So there is no loader needed for type script files.

**Comment by niieani** [comment]
Yes there is. It does not matter what the build target, you always need to transpile TypeScript
