### ISSUE TITLE
Add more info to the "Cannot find module ..." error

### ISSUE THREAD

**Issue by cluka** [aurelia/webpack-plugin#87]
**I'm submitting a feature request**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 2016 Server

* **Node Version:**
6.9.2

* **NPM Version:**
3.10.9

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.28

* **Browser:**
all 

* **Language:**
all

**Current behavior:**
It shows error: Cannot find module './lampostDetails'. + callstack

**Expected/desired behavior:**

I would like to see where did it look for the module. It would be helpful to know the path where it looks for the module being loaded.
IE.
Cannot find module './module2'. Current paths is: '/app/mymodule1'. Searched in: '/app, /app/mymodule1'. 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
It is hard to know where it searches for the modules in a big application when using composition and dynamic modules.

**Comment by EisenbergEffect** [comment]
Unless you configured your module loader differently (using path mapping or something similar) then the location is the same as the module name. This is really loader-specific and not part of Aurelia.

**Comment by EisenbergEffect** [comment]
@niieani Am I correct in the above? or is this some issue with Webpack. When I answered I didn't notice this was a Webpack question...

**Comment by cluka** [comment]
I think this is webpack specific. Don't know if webpack is exposing other info apart the module name. The problem i have is maybe connected to the folder structure i have, where i have multiple levels of subfolders and composites in each of them referencing the modules. IE.:
root\
        folder1\
                    folder1_1
                    folder1_2\
                                    folder1_2_1
                    folder3\
                                 folder3_1
then let's say that in each of those folder i have a view that uses composite wit the same viewModel.
It it throw error: Cannot find module './viewModelName'  then i must go debug which of the view composite cant find it.
Let be clear I'm not reporting a Bug here, just an idea that can help.

**Comment by niieani** [comment]
The new Webpack plugin set should throw clearer errors as it uses Webpack's internal module resolution rather than custom logic. Should be fixed by https://github.com/aurelia/skeleton-navigation/pull/714 and @jods4 future PR to `webpack-plugin`.

**Comment by jods4** [comment]
Yes, the new set of plugins create extra dependencies but their resolution happens entirely in webpack-land.

**Comment by Alexander-Taran** [comment]
https://github.com/aurelia/skeleton-navigation/pull/714 is merged, this should be closed

**Comment by EisenbergEffect** [comment]
Good call! Must have missed this before.
