### ISSUE TITLE
Promise not defined in IE11

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/webpack-plugin#94]
I am using the webpack-plugin and the aspnetcore sample, and it works great in Chrome.

However, when I run in IE, there is no native Promise defined, so it errors out when the bootstrapper runs.

So I include es6-promise in main:

    ```
    import "es6-promise";
    import { Aurelia, PLATFORM } from "aurelia-framework";
   
    export function configure(aurelia: Aurelia) {

    aurelia.use.standardConfiguration()
             .developmentLogging();
    aurelia.start()
         .then(() => aurelia.setRoot(PLATFORM.moduleName("app")));
    ```
However, the aurelia bootstrapper runs before the promise polyfill runs, so the bootstrapper fails.

Is there something else I should be doing?

**Comment by jods4** [comment]
Aurelia requires a Promise polyfill to run in IE.
Like all polyfills, it has to be set up very early, before Aurelia starts.

What I would suggest is that you add `es6-promise-promise` to your NPM dependencies and use Webpack `ProvidePlugin` to inject it where required:
```js
plugins: [
  new AureliaPlugin(),
  new webpack.ProvidePlugin({
    Promise: "es6-promise-promise"
  })
]
```
This is how I do it but there are other ways you can go about it:
- Having a `<script>` tag with all your polyfills first in your page;
- Using multiple entry point and having a module that installs polyfills first: `entry: ["polyfills", "aurelia-bootstrapper"]`
- and probably more if you're creative ;)
