### ISSUE TITLE
Webpack - TypeError: Cannot read property 'used' of null

### ISSUE THREAD

**Issue by jozefizso** [aurelia/webpack-plugin#95]
**I'm submitting a bug report**

* **Library Version:**
2.0.0-rc.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.7.0

* **NPM Version:**
3.10.3

* **Webpack Version**
webpack 2.2.1

* **Browser:**
none

* **Language:**
TypeScript 2.2

**Current behavior:**
I've tried to upgrade `aurelia-webpack-plugin` in a project based on yeoman `generator-aspnetcore-spa`.
I've removed the `aurelia-bootstrapper-webpack` and upgraded webpack, aurelia-webpack-plugin and other packages.
I've update code to use the new AureliaPlugin class.

Webpack configuration is available here: https://gist.github.com/jozefizso/cfcf7a2f58541a71279b3c4952e09586

When I run `webpack --config webpack.config.js`, it will fail on null object in `FlagDependencyUsagePlugin.js`.
Removing `new AureliaPlugin()` from plugins in webpack config will remove the error, but.

```
c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:68
                                var oldUsed = module.used;
                                                    ^

TypeError: Cannot read property 'used' of null
    at processDependency (c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:68:25)
    at c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:51:6
    at Array.forEach (native)
    at processDependenciesBlock (c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:50:27)
    at Compilation.<anonymous> (c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:27:5)
    at Compilation.applyPluginsBailResult1 (c:\dev\samples\AspnetSpa1\node_modules\tapable\lib\Tapable.js:120:27)
    at Compilation.seal (c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\Compilation.js:562:9)
    at c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\Compiler.js:474:16
    at c:\dev\samples\AspnetSpa1\node_modules\tapable\lib\Tapable.js:225:11
    at _addModuleChain (c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\Compilation.js:472:11)
    at processModuleDependencies.err (c:\dev\samples\AspnetSpa1\node_modules\webpack\lib\Compilation.js:443:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

* **What is the expected behavior?**
The webpack with AureliaPlugin should compile the application files.

**Comment by EisenbergEffect** [comment]
@jods4 I think you mentioned that you had a setup for the ASP.NET JavaScript services. Could you help out @jozefizso and then see about getting the Microsoft generator updated with the new stuff when you think it's ready?

**Comment by jozefizso** [comment]
PS: I could build samples from https://github.com/jods4/aurelia-webpack-build and https://github.com/nathanchase/super-minimal-aurelia

**Comment by jods4** [comment]
One thing that is definitely wrong here is that you need `AureliaPlugin` (with `aureliaApp: undefined`) in your DLL since it includes Aurelia libs. Have a look at my DLL demo and the wiki page. 

I am not sure if that might cause the error you see. But maybe it can cause the DLL to lack some internal dynamic dependencies and that turns into `null` modules?

If the error is not fixed after that, it would be helpful to have more info because nothing else strikes me as odd in your config.
- can you debug the build and get an idea of which module is (tentatively) being processed when it crashes?
- can you provide a complete repro?

**Comment by jozefizso** [comment]
Thanks, this did the trick:

**Comment by jozefizso** [comment]
Sample project which does not work is here: https://github.com/jozefizso/AspnetSpa1/tree/bug/aurelia_webpack2_incorrect_config

Running `webpack` on it will caused the issue - it has `new AureliaPlugin()` in `webpack.config.js`.

**Comment by jods4** [comment]
Your git repo contains two mistakes:
- I doesn't have `new AureliaPlugin({ aureliaApp: undefined })` in `webpack.config.vendor.js`.
- Please use `module.rules` instead of `module.loaders`. It's the same option, but the latter is an undocumented synonym for backward compatibility. I missed it in RC1, I'll support it for the next release to avoid problems when people upgrade but for now please use the new official option names.

With those two changes your project builds on my computer without error.

**Comment by jozefizso** [comment]
I did not realize the entry point in this ASP.NET SPA sample is named **boot**. This causes `webpack` to fail. After changing entry point name I was able to build the project and follow the guide to migrate other stuff.

I use the `module.rules`, I've added calls to `PLATFORM.moduleName()` and I had to tweak CSS rules as mentioned in the guide. Branch with these fixes and a working application is here: https://github.com/jozefizso/AspnetSpa1/tree/release/aurelia_webpack2

**Comment by jods4** [comment]
@jozefizso If everything is working I guess we can close this issue?

I have addressed the `module.loaders` synonym for RC2.
You can change the entry point by passing `aureliaApp: "boot"` to `AureliaPlugin`.

Unless I missed something I don't intent on making further changes.

**Comment by jozefizso** [comment]
Yes, it is working for me. Thanks a lot for help.

**Comment by MeirionHughes** [comment]
Had this error reported on my project after a fresh pull. For future readers: it is likely you are missing npm dependency install.

**Comment by stefan505** [comment]
I got the branch shared by @jozefizso working, but it doesn't play nice with plugins:

```
.Uncaught (in promise) Error: Unable to find module with ID: aurelia-validation
```

Anyone any ideas?

**Comment by jods4** [comment]
Assuming you build with Aurelia plugins 2.0, you should have `.plugin(PLATFORM.moduleName('aurelia-validation'))` somewhere in your code.

**Comment by stefan505** [comment]
@jods4 , I deleted my comment without noticing your reply, yes I sorted it out thanks.

**Comment by netrounds-joakim** [comment]
> Had this error reported on my project after a fresh pull. For future readers: it is likely you are missing npm dependency install.

You mean some specific depdency or what? How do I start to figure out which?

@jozefizso I think you should reopen this ticket. Even if setting it to undefined like you did happened to fix your particular issue it is still bad behavior.

**Comment by jods4** [comment]
@netrounds-joakim 
The original issue was clear and is now working as intended.
If you have a problem please open a new issue and describe what you do and what doesn't work.

**Comment by netrounds-joakim** [comment]
@jods4 ok, yea I now realise this is on **webpack**... The issue for me was that I was missing a **webpack loader**. Instead of giving me a nice "could not find depedency error of <name>" it gives you this very hard to understand error `TypeError: Cannot read property 'used' of null`

So anyone finding this thread. Go through all `require` statements, as well as loaders in your `webpack.config.js` and make sure you actually have it installed. In my case I was missing `"awesome-typescript-loader"`.

**Comment by jods4** [comment]
@netrounds-joakim Depends on where the exception was.

If it is inside `aurelia-webpack-plugin` I'm interested in avoiding it so that Webpack can return a better error message.

If it is inside webpack itself... ¯\\\_(ツ)\_/¯

**Comment by netrounds-joakim** [comment]
@jods4 Seems like it's in webpack itself:

```
)$ webpack
/vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:56
                                        const oldUsed = module.used;
                                                              ^

TypeError: Cannot read property 'used' of null
    at processDependency (/vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:56:28)
    at depBlock.dependencies.forEach.dep (/vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:43)
    at Array.forEach (native)
    at processDependenciesBlock (/vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:28)
    at Compilation.compilation.plugin.modules (/vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:23:6)
    at Compilation.applyPluginsBailResult1 (/vagrant/netrounds/static/aurelia-webpack/node_modules/tapable/lib/Tapable.js:120:27)
    at Compilation.seal (/vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/Compilation.js:571:9)
    at /vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/Compiler.js:493:16
    at /vagrant/netrounds/static/aurelia-webpack/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/vagrant/netrounds/static/aurelia-webpack/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by jods4** [comment]
Indeed. Maybe it's worth reporting to Webpack guys.

**Comment by dmoebius** [comment]
In my case I had
```
    resolve: {
        modules: [path.resolve('), 'node_modules']
    }
```
instead of
```
    resolve: {
        modules: [path.resolve('src'), 'node_modules']
    }
```
so Webpack couldn't find main.ts which is located below src/.

The reason why WebPack would find main.ts previously was because the old version of AureliaPlugin allowed specifying the 'src' property:
```
    plugins: [
        new AureliaPlugin({ root: '.', src: 'src' }),
```
which is no longer allowed and now it's simply:
```
    plugins: [
        new AureliaPlugin(),
```
Anyway, it works now! Hope this helps others.

**Comment by fqyjames** [comment]
can't install as cannot read property 'getReferenceTarget' of null...

**Comment by jods4** [comment]
@fqyjames 
you should open a new issue and provide more details please.

**Comment by synesthesia** [comment]
Unfortunately still seeing this issue:

**package.json**

```
{
  "name": "aureliatest",
  "version": "0.0.0",
  "repository": "",
  "license": "",
  "description": "",
  "devDependencies": {
    "aspnet-webpack": "^2.0.1",
    "aurelia-webpack-plugin": "^2.0.0-rc.5",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.1",
    "html-loader": "^0.4.5",
    "json-loader": "^0.5.4",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.16.1",
    "ts-loader": "^2.3.4",
    "typescript": "^2.4.2",
    "url-loader": "^0.5.8",
    "webpack": "^3.5.6",
    "webpack-hot-middleware": "^2.18.2"
  },
  "dependencies": {
    "aurelia-bootstrapper": "^2.1.1",
    "aurelia-router": "^1.3.0"
  }
}
```
_(I have tried with every version of webpack back to 2.7.0)_

**webpack.config.vendor.js**

```
const path = require("path");
const { DllPlugin } = require("webpack");
const { AureliaPlugin } = require("aurelia-webpack-plugin");

module.exports = {
    entry: {
        vendor: [
            "aurelia-bootstrapper",
            "aurelia-router",
        ],
    },
    output: {
        path: path.resolve("wwwroot/dist"),
        filename: "[name].js",
        library: "[name]_[hash]",
    },
    resolve: {
        extensions: ['.js'],
    },
    plugins: [
        new DllPlugin({
            path: path.resolve("wwwroot/dist", "[name]-manifest.json"),
            name: "[name]_[hash]",
        }),
        new AureliaPlugin({ aureliaApp: undefined }),
    ],
};

```
when I run ```node_modules/.bin/webpack --config webpack.config.vendor.js ```

I get

```
D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:56
                                        const oldUsed = module.used;
                                                              ^

TypeError: Cannot read property 'used' of null
    at processDependency (D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:56:28)
    at depBlock.dependencies.forEach.dep (D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:46:43)
    at Array.forEach (<anonymous>)
    at processDependenciesBlock (D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:46:28)
    at Compilation.compilation.plugin.modules (D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\FlagDependencyUsagePlugin.js:23:6)
    at Compilation.applyPluginsBailResult1 (D:\dev\web\aureliatest\src\aureliatest\node_modules\tapable\lib\Tapable.js:140:27)
    at Compilation.seal (D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\Compilation.js:588:9)
    at applyPluginsParallel.err (D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\Compiler.js:514:17)
    at D:\dev\web\aureliatest\src\aureliatest\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\dev\web\aureliatest\src\aureliatest\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

This is on Windows 8.1, with node 8.4.0 and npm 5.0.3 (reverted npm because of [this](https://github.com/npm/npm/issues/18380))

Is the consensus that this is a Webpack issue?

**Comment by jods4** [comment]
@synesthesia 
So far it seems this has always been a user error that is not caught by Webpack and results in an unhelpful crash.

So I would say consensus is that it's a Webpack issue, yes.

**Comment by daattaa** [comment]
a fix for me was on this line 
`new AureliaPlugin({ aureliaApp: undefined }),`
You have undefined, an example I found [here](https://github.com/EisenbergEffect/aspnetcore-aurelia-build-2017) used 'boot' and for my application i needed to set it to 'main' corresponding to the aurelia config file.

**Comment by jods4** [comment]
This attribute is a module that is added to the list of aurelia-loaded module that have to be included in your main chunk.
Specifically, it's meant to reflect the `aurelia-app` attribute in your main html file, as this file is normally not processed by Webpack.

Setting the config to `undefined` means you don't use `aurelia-app` or at least you don't need to include it because you took care of this some other way.
