### ISSUE TITLE
TypeError: AureliaWebpackPlugin is not a constructor

### ISSUE THREAD

**Issue by HamedFathi** [aurelia/webpack-plugin#97]
I used Microsoft Aurelia template with ASP.NET Core
[https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/](https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/)

**dotnet new aurelia**

All things work perfectly ! but before update package.json !

in old 'package.json' template used 
```
"webpack": "2.1.0-beta.25",
"aurelia-webpack-plugin": "^1.1.0",
```
and in new 
```
"webpack": "2.3.2",
"aurelia-webpack-plugin": "^2.0.0-rc.1",
```

I updated library one by one, after updating 'webpack' to latest version still All things worked
but after updating 'aurelia-webpack-plugin' to latest version the error occured.

I ran the 'webpack' command and got the error :
```
C:\Users\...\Desktop\AuProj>webpack
C:\Users\...\Desktop\AuProj\webpack.config.js:30
        new AureliaWebpackPlugin({
        ^

TypeError: AureliaWebpackPlugin is not a constructor
    at Object.<anonymous> (C:\Users\...\Desktop\AuProj\webpack.config.js:30:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\...\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:39:40)
```

**Webpack.config.js**

```
var isDevBuild = process.argv.indexOf('--env.prod') < 0;
var path = require('path');
var webpack = require('webpack');
var AureliaWebpackPlugin = require('aurelia-webpack-plugin');

var bundleOutputDir = './wwwroot/dist';
module.exports = {
    resolve: { extensions: [ '.js', '.ts' ] },
    entry: { 'app': 'aurelia-bootstrapper-webpack' }, // Note: The aurelia-webpack-plugin will add your app's modules to this bundle automatically
    output: {
        path: path.resolve(bundleOutputDir),
        publicPath: '/dist',
        filename: '[name].js'
    },
    module: {
        loaders: [
            { test: /\.ts$/, include: /ClientApp/, loader: 'ts-loader', query: { silent: true } },
            { test: /\.html$/, loader: 'html-loader' },
            { test: /\.css$/, loaders: [ 'style-loader', 'css-loader' ] },
            { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
            { test: /\.json$/, loader: 'json-loader' }
        ]
    },
    plugins: [
        new webpack.DefinePlugin({ IS_DEV_BUILD: JSON.stringify(isDevBuild) }),
        new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('./wwwroot/dist/vendor-manifest.json')
        }),
        new AureliaWebpackPlugin({
            root: path.resolve('./'),
            src: path.resolve('./ClientApp'),
            baseUrl: '/'
        })
    ].concat(isDevBuild ? [
        // Plugins that apply in development builds only
        new webpack.SourceMapDevToolPlugin({
            filename: '[file].map', // Remove this line if you prefer inline source maps
            moduleFilenameTemplate: path.relative(bundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
        })
    ] : [
        // Plugins that apply in production builds only
        new webpack.optimize.UglifyJsPlugin()
    ])
};

```

![untitled](https://cloud.githubusercontent.com/assets/8418700/24342750/14ac979c-12d8-11e7-8277-3a75d20b15ac.png)

Why did I update the 'aurelia-webpack-plugin' to latest version the error happen ?
Can someone help me how to resolve the issue ?

**Comment by jods4** [comment]
Version 2.x is a complete redesign of the 1.x plugins and it's not meant to be backward-compatible.

If you want to upgrade I suggest that you start by reading the information available here:
https://github.com/jods4/aurelia-webpack-build/wiki

**Comment by kdekooter** [comment]
@jods4 using the same dependencies as the OP:  webpack 2.3.2 and aurelia-webpack-plugin 2.0.0-rc.1 I run into the exact same error

```
    new AureliaWebpackPlugin(),
    ^

TypeError: AureliaWebpackPlugin is not a constructor
```

**Comment by kdekooter** [comment]
@jods4 using the same dependency versions as the OP, running from a clean node_modules directory the error still pops up.

**Comment by jods4** [comment]
@kdekooter Because there is no `AureliaWebpackPlugin` in `aurelia-webpack-plugin` 2.0, by design.
If you upgrade to 2.0 please read the documentation linked above and have a look at the examples in that repo.

**Comment by kdekooter** [comment]
@jods4 I get it now, two curly braces make all the difference: `const { AureliaPlugin } = require('aurelia-webpack-plugin')` vs `const AureliaPlugin = require('aurelia-webpack-plugin')`
